### ISSUE TITLE
MultiWayIf formatted with four spaces

### ISSUE THREAD

**Issue by oberblastmeister** [tweag/ormolu#1002]
**Describe the bug**
```haskell
testing =
  if
    | otherwise -> ()
    | otherwise -> ()
    | otherwise -> ()
```

gets formatted into this

```haskell
testing =
  if
      | otherwise -> ()
      | otherwise -> ()
      | otherwise -> ()
```

**Expected behavior**
It should not be formatted with four spaces.

**Environment**
 - OS name + version: Arch Linux
 - `ormolu 0.5.3.0 1b39d94d0c06aa53a577f7e0476695f9e6f5020b
using ghc-lib-parser 9.4.3.20221104`

**Comment by mrkkrp** [comment]
There is a reason for this, see #488.

**Comment by amesgen** [comment]
Yeah, I wonder whether we might want to revisit that, given that we have the same problem with `do`:
```haskell
testing = 
  do
    succ
   1
```

In https://github.com/tweag/ormolu/issues/707#issuecomment-888359615, we decided that this should be a fixed point, as indenting the bodies of `do` blocks by 4 spaces to account just due to this edge case seems to be more severe than violating our "indentation should be divisible by 2" principle.

From a consistency standpoint, shouldn't we change `MultiWayIf` to also use only 2 spaces and accept the 1 space indentation if an argument is applied to it? WDYT?

**Comment by mitchellwrosen** [comment]
> From a consistency standpoint, shouldn't we change MultiWayIf to also use only 2 spaces and accept the 1 space indentation if an argument is applied to it? WDYT?

I agree with this. Aside: I have never even seen code that applies the RHS of a multi-way if to an argument; I didn't know it was possible. :sweat_smile:

**Comment by mrkkrp** [comment]
Note that if we start using 1 space, then whatever is nested inside that 1-space-indented block is going to be at odd (literally) indentations: 3, 5, etc., and it this kind of code block can be potentially large, which is the worst.

I do understand the consistency argument though.

**Comment by amesgen** [comment]
Another alternative that would fix this issue and also improve consistency: What about identing `do` blocks/`case`s/MultiWayIf with with 4 spaces iff it is the applicand (i.e. the RHS of an application)?

I.e. this would be a fixed point, note how applied `do` blocks and MultiWayIf are now formatted consistently compared to the current output, and `foo1` no longer has odd indentation:

<table>
<tr>
<th>
Proposed fixed point
</th>
<th>
Current output
</th>
</tr>
<tr>
<td>

```haskell
foo0 =
  do
    2

foo1 =
  do
      succ
    1

foo2 =
  if
    | otherwise -> 2

foo3 =
  if
      | otherwise -> succ
    1
```

</td>
<td>

```haskell
foo0 =
  do
    2

foo1 =
  do
    succ
   1

foo2 =
  if
      | otherwise -> 2

foo3 =
  if
      | otherwise -> succ
    1
```

</td>
</tr>
</table>

**Comment by mrkkrp** [comment]
@amesgen I quite like this idea.
