### ISSUE TITLE
Multiple functions in single signature results in odd behaviour

### ISSUE THREAD

**Issue by ruhatch** [tweag/ormolu#104]
I have two cases here, the first a bit less contrived than the second:
```
fst, snd :: Bool
(fst, snd) = (True, False)

fst, snd :: Bool
fst = True
snd = False
```
which gives:
```
fst, snd :: Bool

(fst, snd) = (True, False)

fst, snd :: Bool
fst = True

snd = False
```
The first should definitely not have the newline. The second is clearly more tricky, but I actually think we should keep them together if that's how people choose to write it.

**Comment by utdemir** [comment]
In this case it makes sense to group them together. However, as you mentioned more complex examples get tricky, for example:

```haskell
foo = undefined
bar = undefiend
{-# DEPRECATED foo, bar ".." #-}
```

or even more complex things like:

```haskell
f1 = undefined
f1, f2 :: Bool
f2 = undefined
{-# DEPRECATED f2, f3 ".." #-}
f3 :: Bool
f3 = undefined
```

I think, we can just handle the (hopefully) common case where we:

1. Pick the first declaration, and get the names it mentions.
2. Group that with all the following declarations referring to any of the names.
3. As soon as we get a declaration which does not refer to anything in the initial declaration, put a blank line.

It is not perfect, but I guess it will make sense for common uses.
