### ISSUE TITLE
Ormolu doesn't take Cabal mixins into account

### ISSUE THREAD

**Issue by brandonchinn178** [tweag/ormolu#1052]
**Describe the bug**
The issue in #1032 still occurs if the `base` dependency is imported from a common stanza

**To Reproduce**
```cabal
name: foo
version: 0

common base
  build-depends: base

library
  import: base
  exposed-modules: Foo
```
```hs
module Foo where

foo :: Int
foo =
  (+ 1) $
    (+ 2) $
      3
```

Ormolu returns
```diff
  foo :: Int
  foo =
-   (+ 1) $
-     (+ 2) $
-       3
+   (+ 1)
+     $ (+ 2)
+     $ 3
```

**Expected behavior**
The snippet should not reformat.

**Environment**
 - OS name + version:
 - Version of the code:

**Additional context**

**Comment by amesgen** [comment]
Hmm, thanks for the report, but I don't think this is related to Ormolu; rather, common stanzas were introduced in [`cabal-version: 2.2`](https://cabal.readthedocs.io/en/stable/file-format-changelog.html#cabal-version-2-2), but as you don't specify a `cabal-version`, the common stanza is (silently?) ignored. When I add
```cabal
cabal-version: 2.2
```
to the top of your `.cabal` file, Ormolu formats the module as one would expect (i.e. it stays as it is).

Does that make sense?

**Comment by brandonchinn178** [comment]
Ah you're right, sorry about the false positive.
