### ISSUE TITLE
Overloaded labels (hash) syntax gets formatted with space after hash sign

### ISSUE THREAD

**Issue by zzantares** [tweag/ormolu#1078]
**Describe the bug**

Formatting a file that uses overloaded labels without declaring the `OverloadedLabels` extension in the file, inserts a space after hash sign after formatting.

**To Reproduce**

Given this file:

```haskell
{-# LANGUAGE DataKinds #-}

module Web.Controller.Posts where

import Data.Function ((&))

(|>) = (&)

validateField = undefined

nonEmpty = undefined

title = undefined

buildPost post =
  post
    |> validateField #title nonEmpty
```

Using `ormolu sample.hs` to format it results in (note the extra space in `# title`:

```haskell
{-# LANGUAGE DataKinds #-}

module Web.Controller.Posts where

import Data.Function ((&))

(|>) = (&)

validateField = undefined

nonEmpty = undefined

title = undefined

buildPost post =
  post
    |> validateField
    # title nonEmpty
```

**Expected behavior**
To behave as if the `OverloadedLabels` was explicitly enabled in the file, thus producing this output:

```haskell
{-# LANGUAGE DataKinds #-}

module Web.Controller.Posts where

import Data.Function ((&))

(|>) = (&)

validateField = undefined

nonEmpty = undefined

title = undefined

buildPost post =
  post
    |> validateField #title nonEmpty
```

**Environment**
 - OS name + version: `Ubuntu 22.04.3 LTS`
 - Version of the code: `ormolu 0.7.2.0 using ghc-lib-parser 9.6.3.20231014`

**Additional context**
This does not occur if the file has `{-# LANGUAGE OverloadedLabels #-}` at the top, but it does when the extension is enabled via the `*.cabal` file.

**Comment by amesgen** [comment]
Can you post a concrete example of the folder structure (`.cabal` file plus Haskell source file) which reproduces the problem?
