### ISSUE TITLE
Format selection containing `->`

### ISSUE THREAD

**Issue by emlautarom1** [tweag/ormolu#1099]
**Describe the bug**
Ormolu is unable to format a selection when it contains a `->` symbol (ex. case expressions)

**To Reproduce**
1. Create a Haskell file with the following code
```haskell
x = case () of
  () ->     ()
```
2. Select the `  () ->     ()` line
3. Use the `Format Selection` command

**Expected behavior**
The code should be formatted to `  () -> ()` (removes the additional spaces between `->` and `()`)

**Environment**
 - OS name + version: Fedora 39 Workstation
 - Version of the code: Whatever is used in HLS 2.5.0.0
 - Editor: VSCode 1.86.1

**Additional context**
Originally, I thought that this problem was with HLS (see: https://github.com/haskell/haskell-language-server/issues/4074) but I was able to narrow it down to Ormolu. The original use case is to format only modified lines, which sometimes can be patterns in case expressions.

**Comment by amesgen** [comment]
Thanks for the report! [Region formatting](https://github.com/tweag/ormolu?tab=readme-ov-file#regions) only works when the selection is still parseable Haskell code on its own, as Ormolu relies on the GHC parser. Hence, we currently don't support your use case.

We could mention this in the corresponding [README paragraph](https://github.com/tweag/ormolu#regions).
