### ISSUE TITLE
Make it clear that configuration files must end with a newline

### ISSUE THREAD

**Issue by mngrm3a** [tweag/ormolu#1122]
**Is your feature request related to a problem? Please describe.**
`.ormolu` files need to end with a newline or the config parser will fail. This isn't clear from the README. It's not a big deal when ormolu is being used from the shell. But when running as a library in hls, it's not immediately obvious what is causing the formatter to fail.

**Describe the solution you'd like**
Make the parser more lenient or add a hint to the readme.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by amesgen** [comment]
Thanks for the report, it sounds simplest to just allow trailing newlines :+1: Opened #1123 for that.
