### ISSUE TITLE
Instance header formatting discussion

### ISSUE THREAD

**Issue by ruhatch** [tweag/ormolu#113]
I'd like to use this issue to discuss various class `instance` layouting questions that arise as we test `ormolu` on more code. I'm currently running it over the various Cardano codebases to find nitpicks. I will label specific examples so we can refer to them more easily.

**Comment by ruhatch** [comment]
# Example 1

## Input

```
instance
    (Applicative m, Monad m, MonadError SchemaError m)
    => ReportSchemaErrors m
  where
```

## Output

```
instance (Applicative m, Monad m, MonadError SchemaError m)
         => ReportSchemaErrors
              m where
```

I'm not sure about this one. I have a couple of concerns.

1. I think that in general if we're going multiline, then we should indent, so I'd suggest not leaving the constraints on the same line as `instance`
2. I don't think the `m` should be on a separate line from `ReportSchemaErrors` here as there's no precedent from the input to put that on multiple lines
3. We should have a general discussion of `where` should go with multiline `class` and `instance` declarations. In this specific case I actually like the input (I wrote it though, so I'm biased ;)

**Comment by yumiova** [comment]
Speaking as the person who arbitrarily picked the pretty printing of instance and type class declarations, I actually entirely agree. The only reason I picked the one we currently have is because it seemed simple to implement, relatively non-controversial (I had seen it in some Haskell code) and there wasn't really any prior style to point to. But in general, I am not particularly fond if it myself.

Also, solving the problem in question 2 is, I believe, not directly related to formatting of instances but rather formatting of types + contexts, since instance formatting just reuses the pretty printing logic of type ascriptions.

**Comment by yumiova** [comment]
For the record, type families are currently formatted as

```haskell
type family
  Id a
    = result
    | result -> a where
```

If we want to keep things consistent with this, then intuitively the given instance should be formatted as

```haskell
instance
  (Applicative m, Monad m, MonadError SchemaError m)
  => ReportSchemaErrors m where
```

or

```haskell
instance
  (Applicative m, Monad m, MonadError SchemaError m)
    => ReportSchemaErrors m where
```

This has problems of readability all of its own, but figured I might as well put it out there.

**Comment by aspiwack** [comment]
> ```haskell
> instance
>   (Applicative m, Monad m, MonadError SchemaError m)
>   => ReportSchemaErrors m where
> ```

For what it's worth, I believe this to be the right output for that input.

**Comment by ruhatch** [comment]
When the constraints are in multi-line mode, does this look reasonable?
```
instance
  ( Applicative m
  , Monad m
  , MonadError SchemaError m
  ) 
  => ReportSchemaError m where

**Comment by ruhatch** [comment]
@aspiwack I just realised that there was no body in that instance, and I'm not sure it so readable when you add that in:
```
instance
  (Applicative m, Monad m, MonadError SchemaError m)
  => ReportSchemaErrors m where
  function = here is the body == something else
```
so I might suggest
```
instance
  (Applicative m, Monad m, MonadError SchemaError m)
  => ReportSchemaErrors m 
 where
  function = here is the body == something else
```
The argument for `where` with one space is relatively strong here I think, I allows the body of the instance to remain where it is while increasing readability of the head.

**Comment by aspiwack** [comment]
My bias would be for

```haskell
instance
  (Applicative m, Monad m, MonadError SchemaError m)
  => ReportSchemaErrors m 
  where
    function = here is the body == something else
```

That is: `where` aligned with the arrow, definitions indented two spaces.

Or, possibly

```haskell
instance
    (Applicative m, Monad m, MonadError SchemaError m)
    => ReportSchemaErrors m 
  where
    function = here is the body == something else
```

That is: signature indented 4 spaces from `instance`, `where` indented only two, and `function` indented 4 spaces again (that's 2 more than `where`, like  in the previous suggestion).

**Comment by ruhatch** [comment]
I think it would be a real shame if your diff got bloated because the entire instance body had to be indented though

**Comment by ruhatch** [comment]
Also indenting the entire instance body is really bad for rebases, because it can lead to nonsense indentation and parse errors

**Comment by aspiwack** [comment]
Ah. So your point is that if I have a single line instance

```haskell
instance Context => Head where
  function = body
```

And the instance declaration would suddenly become multiline

```haskell
instance
    Context
    => Header
  where
    function = body
```

We would have to reindent all of `function = body`, and that'd fail at the diff-minimisation metric.

Fine.

But there is another solution: always indent the function 4 spaces, even in the single line example:

```haskell
instance Context => Head where
    function = body
```

**Comment by ruhatch** [comment]
That is another option, yeah. So I guess it's a choice between non-standard indentation for the `where` at 1 space or the instance body at 4 spaces. Can we gather some specific pros and cons of each?

I suppose one argument for `where` spacing is that an existing codebase with 2-space indented instance bodies would have a smaller diff running `ormolu` on the whole codebase, but I'm not sure if that's a case we're trying to optimise for.

**Comment by aspiwack** [comment]
The [Tweag style guide](https://github.com/tweag/guides/blob/master/style/Haskell.md) specifies that function bodies should be indented 4 spaces for instance (all so that you can deindent the `where` clause to 2 spaces).

Indenting instance methods 4 space is somewhat consistent with this bit (though the style guide also says 2 spaces everywhere except declarations).

I'm inclined to favour multiples-of-two indentation everywhere, because indentations of 1 are hard to see.

On the other hand, in my experience, most `instance … where` are single line, and we would be imposing the very long 4 space (that'd be 8 spaces for the function bodies!) on all of these, for the rarer occasion where the `instance … where` is multiline.

**Comment by yumiova** [comment]
According to @mrkkrp in #120, instance and type class declarations should include a newline before the first declaration. Consequently, I wonder what people think about the first example with this change:

```haskell
instance
  (Applicative m, Monad m, MonadError SchemaError m)
  => ReportSchemaErrors m where

  function = here is the body == something else

  otherFunction x = x
```

**Comment by mrkkrp** [comment]
That looks good. In case of multiline constraint it would be:

```haskell
instance
  (Applicative m
  , Monad m
  , MonadError SchemaError m
  )
  => ReportSchemaErrors m where

  function = here is the body == something else

  otherFunction x = x
```

@yumiova Can you open a PR implementing the change?

**Comment by yumiova** [comment]
@mrkkrp Sure, I should get it done soon.

**Comment by yumiova** [comment]
OK, I am done adapting the formatting in #135. If anyone would like further changes, feel free to ping me again.
