### ISSUE TITLE
AST differs for quasi-quoted type application

### ISSUE THREAD

**Issue by p4l1ly** [tweag/ormolu#1134]
**Describe the bug**
The code
```
foo = foo @[k|bar|]
```
formats to
```
foo = foo @ [k|bar|]
```
which is wrong because `@[k|bar|]` is a type application but `@ [k|bar|]` is an operator application.

**To Reproduce**
Via Ormolu Live.

**Expected behavior**
Not inserting space after `@`.

**Environment**
Version 0.7.7.0, commit [392b2bc](https://github.com/tweag/ormolu/commit/392b2bce17fb0c8895afd5cc619bba39c51b8ea0), using ghc-lib-parser 9.10.1.20240511

**Comment by amesgen** [comment]
Thanks! Fix is in #1135 :+1:
