### ISSUE TITLE
Error on functions with a single guard

### ISSUE THREAD

**Issue by utdemir** [tweag/ormolu#124]
Given input:

```
baz x | x == 5 = 10
```

Ormolu produces (with `--unsafe` flag):

```
baz x = | x == 5 = 10
```

Which is not valid Haskell.

---

I might be wrong, but the issue might be about this conditional, since it works fine if there are multiple guards: 

https://github.com/tweag/ormolu/blob/4a0e5d4e422665dfd207451321f748e7b5dbb8d1/src/Ormolu/Printer/Meat/Declaration/Value.hs#L135-L140

**Comment by ethercrow** [comment]
Input

```
fixHue :: Double -> Double
fixHue h | h >= 0 && h < 360 = h
fixHue h | h >= 360 = fixHue $ h - 360
fixHue h = fixHue $ h + 360
```

Output

```
fixHue :: Double -> Double
fixHue h = | h >= 0 && h < 360 = h
fixHue h = | h >= 360 = fixHue $ h - 360
fixHue h = fixHue $ h + 360
```

**Comment by mrkkrp** [comment]
This one should be sufficiently easy to investigate and fix. If anyone is looking what to hack on, try this.
