### ISSUE TITLE
Type operator output with fully qualified name

### ISSUE THREAD

**Issue by ruhatch** [tweag/ormolu#126]
Here is the diff from a type signature that replaced the `~` operator with its fully qualified version:
```
 mapBuilderJson
-  :: (Exts.IsList t, Exts.Item t ~ (k, v), Buildable k, Buildable v)
+  :: (Exts.IsList t, Exts.Item t Data.Type.Equality.~ (k, v), Buildable k, Buildable v)
   => t
   -> Builder
```

**Comment by mrkkrp** [comment]
This one should be sufficiently easy to investigate and fix. If anyone is looking what to hack on, try this.
