### ISSUE TITLE
Emacs package for ormolu

### ISSUE THREAD

**Issue by vyorkin** [tweag/ormolu#132]
I've created a very basic emacs package to format code with `ormolu`: https://github.com/vyorkin/ormolu.el. Just letting you know in case you want to add a link to the README ;)

**Comment by mrkkrp** [comment]
Thanks! I'll try to evaluate it when I have time. There always has been a plan to create something like this, but little thought has been put into actually designing such a package, because we need to get the tool itself right (well, sufficiently right) first.

**Comment by tuncer** [comment]
@vyorkin, this looks useful. I stumbled on this ticket while [attempting to customize](https://github.com/lassik/emacs-format-all-the-code/issues/30#issuecomment-508157652) format-all.el, which defaults to brittany.

@mrkkrp, any thoughts on allowing `optInputFile` to be `Nothing` (stdin) or `-` (stdin)?

**Comment by mrkkrp** [comment]
@tuncer I'm not against the feature, you can go ahead and open a PR for that.

**Comment by tuncer** [comment]
@mrkkrp see #150

**Comment by mrkkrp** [comment]
I mentioned the package in the readme.
