### ISSUE TITLE
Sorting of prelude imports results in AST differences between original and formatted code

### ISSUE THREAD

**Issue by eschnett** [tweag/ormolu#141]
I received this error message from ormolu:
```
$ ormolu src/Poisson.hs
AST of input and AST of formatted code differ.
Please, consider reporting the bug.
```

The original source code is available at https://gist.github.com/eschnett/2ee64cfb7dea77b8c69bd37eeaef5744 .

Is there a way to help debug this? For example, is there a way to make ormolu output the two ASTs, or maybe the formatted ASTs?

**Comment by yumiova** [comment]
To get the relavant invalid abstract syntax tree, call ormolu with the `-u`/`--unsafe` command line flag:

```
$ ormolu -u src/Poisson.hs
```

**Comment by eschnett** [comment]
This source code is much shorter:
```
module P where

import Prelude hiding (id, (.))
import qualified Prelude
```
