### ISSUE TITLE
Drop trailing white space in comments?

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#146]
Would it be a good idea? What do you think?

**Comment by sphaso** [comment]
Sometimes trailing whitespaces are significant, e.g. if the comment is being rendered in a markdown file. I don't know how significant this scenario is, but I would rather keep the whitespaces.

**Comment by mboes** [comment]
Significant *trailing* whitespace, or just significant whitespace?

**Comment by mboes** [comment]
I think it's a good idea to drop trailing whitespace everywhere (i.e. do what `delete-trailing-whitespace` in Emacs does, essentially).

**Comment by drathier** [comment]
In Markdown trailing whitespace is significant. It's how you print a newline character.

**Comment by mrkkrp** [comment]
It is one way to print the newline character, but should be care? Haddock is not a markdown document.

**Comment by mboes** [comment]
It's arguably a misfeature of Markdown, Haddock isn't Markdown to begin with, and there is a normative advantage to avoiding extraneous whitespace.
