### ISSUE TITLE
Support data types with infix & multi-line declarations

### ISSUE THREAD

**Issue by yumiova** [tweag/ormolu#151]
Currently, data type declarations such as

```haskell
data (f :* g) a
```

gets reformatted into

```haskell
data :* f g a
```

Presumably because data types are currently not formatted in terms of `p_infixDefHelper`.

That said, there is a in-progress branch in [yumiova:yumiova/infix-data-operators](https://github.com/yumiova/ormolu/tree/yumiova/infix-data-operators) that fixes this. The branch is close to done, but one syntactic question remains:

Should cases like

```haskell
data
  (f :+ g)
    a
  = L (f a)
  | R (g a)
```

be kept as is, or converted into some other form (e.g., with an extra indentation before the cases?)

The current approach would minimise diffs, but may cause certain cases to be difficult to read:

```haskell
data
  (f :* g) a
  = f a :* g a
```

**Comment by mrkkrp** [comment]
> be kept as is, or converted into some other form

I think it's OK to keep it in this form.

**Comment by mrkkrp** [comment]
I ran into this yesterday when I tried to run Ormolu on some real-world sources. How the fix is going?

**Comment by yumiova** [comment]
I will be sending a pull request for both this and transform list comprehensions in a few hours.

**Comment by mrkkrp** [comment]
Thanks! Didn't mean to hurry you or something, just wanted to check on the status ;)
