### ISSUE TITLE
Testing on code from Hackage

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#160]
Devise a method to run Ormolu on all or most packages found on Hackage. For that:

1. Download Hackage index.
2. Go through packages.
3. Select just source files.
4. Use standalone C preprocessor command to drop any CPP.
5. Run every file through Ormolu automatically logging problems.

**Comment by domenkozar** [comment]
Won't this require parsing extensions from Cabal files?

**Comment by mrkkrp** [comment]
It should not, mostly, see: https://github.com/tweag/ormolu/pull/157

**Comment by neongreen** [comment]
It would also be worth to go through the Hindent testsuite (https://github.com/chrisdone/hindent/blob/master/TESTS.md) first – it has many tricky mostly-minimal examples.
