### ISSUE TITLE
Remove language extension whitelist

### ISSUE THREAD

**Issue by mboes** [tweag/ormolu#163]
In an effort to resolve #62 and other issues, #157 introduced an explicit list of extensions to turn on by default. This list is hard-coded, and moreover can't be configured, since that's what #157 also does: remove configurability (and rightly so). But if we're going to remove configurability, we should be extremely permissive about the inputs we allow.

As argued in https://github.com/tweag/ormolu/issues/62#issuecomment-497339902, we shouldn't need to whitelist extensions. Even keyword-stealing extensions should be fine, because it's not like we intend to format AST's differently based on whether some identifier is actually a keyword or not. Or at least - I can't think of an extension for which that would be true.

**Comment by mrkkrp** [comment]
We certainly can't enable all of them at once. Examples that I discovered today include:

* `ViewPatterns` and `PatternSynonyms` do conflict because the syntax for view patterns is in conflict with the syntax for unidirectional pattern synonyms.
* Magic hash in some cases has a weird effect on `{-# things like this #-}`.

There may be more. I'm not afraid of letting `proc` or something like this to be stolen really, but those conflicts above just break the tool.

**Comment by mboes** [comment]
Yes but managing a small set of conflicting extensions is much easier than managing a set of those that don't. The GHC Proposals Committee is on record for being against conflicting extensions, so we likely won't be seing many more of those in the future.

`-XMagicHash` is one of those few ones that shouldn't be enabled by default, because the format for `f# 1` will be very different depending on whether that occurrence of `#` stands for an operator or not.

**Comment by mrkkrp** [comment]
So to make it clear: you want a blacklist instead of whitelist?

**Comment by mboes** [comment]
Yes. The vast majority of extensions can safely be turned on without conflict, vs a tiny subset that does conflict. So better to blacklist than to whitelist.

**Comment by mboes** [comment]
BTW do you have an example of conflict between `-XPatternSynonyms` and `-XViewPatterns`? I could not reproduce.

**Comment by mrkkrp** [comment]
I'll show you tomorrow.

**Comment by mrkkrp** [comment]
Actually I started digging that pattern synonyms stuff and found it to be a bug in Ormolu. The fix is coming.

**Comment by mrkkrp** [comment]
Note: when done with this, add something to the docs and readme about which extensions are enabled by default.

**Comment by waddlaw** [comment]
How about adding an option to print out a list of language extensions that are enabled by default?

**Comment by mrkkrp** [comment]
It looks like a good idea to me.
