### ISSUE TITLE
Comments are moved outside of lists, causing sanity check failure

### ISSUE THREAD

**Issue by neongreen** [tweag/ormolu#174]
```haskell
main :: IO ()
main = do
    migrateSchema
        [ migration1
        , migration1
        , migration3
        -- When adding migrations here, don't forget to update
        -- 'schemaVersion' in Galley.Data
        ]
      `finally`
        Log.close
```

Formatting this code results in "AST of input and AST of formatted code differ". Formatting with `-u` results in:

```haskell
main :: IO ()
main = do
  migrateSchema
    [ migration1
    , migration1
    , migration3
    ] -- When adding migrations here, don't forget to update
  -- 'schemaVersion' in Galley.Data
  `finally`
    Log.close
```

**Comment by mrkkrp** [comment]
I don't think we can do much about the fact that the comment is moved outside of the list. However, something is clearly wrong with indentation level: each argument of `migrateSchema` should start at the same level, so no matter what happens the second line of the comment and `finally` should start at the same column as `[`. Let's see if I can fix this.
