### ISSUE TITLE
Parentheses in "deriving (MonadReader r)" are dropped

### ISSUE THREAD

**Issue by neongreen** [tweag/ormolu#195]
Input:

```haskell
{-# LANGUAGE StandaloneDeriving #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}

import Control.Monad.Reader

newtype R r a = R (ReaderT r IO a)
  deriving (MonadReader r)

deriving instance Functor (R r)
deriving instance Applicative (R r)
deriving instance Monad (R r)
```

Output:

```haskell
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE StandaloneDeriving #-}

import Control.Monad.Reader

newtype R r a = R (ReaderT r IO a)
  deriving MonadReader r

deriving instance Functor (R r)

deriving instance Applicative (R r)

deriving instance Monad (R r)
```

**Comment by mrkkrp** [comment]
This is not a problem, right? I think we do it on purpose as a “normalization” measure.

**Comment by mboes** [comment]
Arguably `deriving` should always have parens.

**Comment by mrkkrp** [comment]
My logic is that if we can go without parens we should do it. The same happens for constraints I think. He intuition is that when something is not necessary it is good to do normalisation and drop it. @mboes what’s the motivation for having parens there?

**Comment by mboes** [comment]
Some people put parens on both (deriving and constraints in type signatures). Reason being: less work when you have to invariably edit the constraint list to add another one. Not a particularly important style choice. We could go either way.

**Comment by neongreen** [comment]
This is a problem because the resulting code doesn't parse: `parse error on input ‘r’`. I should've mentioned that.

**Comment by mrkkrp** [comment]
Then this is a bug. It may make sense to go with parens everywhere for consistency then.
