### ISSUE TITLE
Broken layout for multiline patterns in case matches

### ISSUE THREAD

**Issue by neongreen** [tweag/ormolu#198]
This one is from pandoc (severely reduced).

Input:

```haskell
readerBench doc name =
  runPure $ case (getReader name, getWriter name) of
    (Right (TextReader r, rexts),
     Right (TextWriter w, wexts))  -> undefined
```

Output:

```haskell
readerBench doc name =
  runPure $ case (getReader name, getWriter name) of
    ( Right (TextReader r, rexts)
    , Right (TextWriter w, wexts)
    )  -> undefined
```

```
4:5: error: …
    parse error (possibly incorrect indentation or mismatched brackets)
```

**Comment by neongreen** [comment]
Note that since Pandoc is GPL-ed, you probably shouldn't paste this example into your testsuite verbatim. Same goes for some previous examples that come from wire-server.

**Comment by mboes** [comment]
If it's just a few lines of example code for testing/documentation purposes then that shouldn't be a concern: https://www.gnu.org/licenses/gpl-faq.en.html#SourceCodeInDocumentation.
