### ISSUE TITLE
Inconsistent indentation of multiline expressions in lists, tuples, and parentheses

### ISSUE THREAD

**Issue by neongreen** [tweag/ormolu#201]
Input:

```haskell
handleStuff =
  handle
    [ \ExceptionA ->
        something
    , \ExceptionB ->
        somethingElse
    ]
```

Output:

```haskell
handleStuff =
  handle
    [ \ExceptionA ->
        something
    , \ExceptionB ->
      somethingElse
    ]
```

I think it would be best if both lambdas were formatted like the first lambda.

**Comment by neongreen** [comment]
Affects other expressions too, actually.

Input:

```haskell
handleStuff =
  handle
    [ foo
        bar
    , baz
        qux
    ]
```

Output:

```haskell
handleStuff =
  handle
    [ foo
        bar
    , baz
      qux
    ]
```

**Comment by neongreen** [comment]
The behavior with `let` is worse, and might hint at another bug:

```haskell
handleStuff =
  ( let foo = foo
     in foo
  , let bar = bar
     in bar
  )
```

```haskell
handleStuff =
  ( let foo = foo
     in foo
  , let bar = bar
   in bar
  )
```

**Comment by neongreen** [comment]
Interestingly, with only one element in parentheses we get incorrect behavior, not the correct one:

```haskell

handleStuff =
  ( let foo = foo
     in foo
  )
```

```haskell
handleStuff =
  ( let foo = foo
   in foo
  )
```

**Comment by yumiova** [comment]
I have noticed earlier that lone function calls in parentheses also gets formatted as

```haskell
foo =
  ( function
    argument1
    argument2
  )
```

Should this not be indented?

I was unsure if this was intended or not, but with this problem appearing inconsistently in list expressions and tuples, surely this is accidental?

The eventual fix likely requires adding `sitcc` in the relevant places.

**Comment by mrkkrp** [comment]
> The eventual fix likely requires adding sitcc in the relevant places.

Correct.

**Comment by yumiova** [comment]
For the record, I have a rough fix implemented a few week ago for personal use in [yumiova:yumiova/indented-parentheses](https://github.com/yumiova/ormolu/tree/yumiova/indented-parentheses)
