### ISSUE TITLE
Preserve comments on language pragmas

### ISSUE THREAD

**Issue by neongreen** [tweag/ormolu#216]
Input:

```haskell
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE PackageImports #-}

-- FIXME: We need this for such-and-such stupid reason. Ideally we should
-- fix it with this-and-this approach.
{-# LANGUAGE ExtendedDefaultRules #-}

module Foo where
```

Output:

```haskell
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE ExtendedDefaultRules #-}
{-# LANGUAGE PackageImports #-}

-- FIXME: We need this for such-and-such stupid reason. Ideally we should
-- fix it with this-and-this approach.
module Foo where
```

This means that I can't document tricky/unpleasant exceptions for other code readers.

**Comment by mrkkrp** [comment]
This seems to be in a conflict with the idea of automated grouping of language pragmas.

**Comment by basile-henry** [comment]
The pragmas could only be sorted by groups split using comments as delimiters.

This is similar to what `stylish-haskell` does with imports (and maybe also language pragmas) as far as I remember. Though it uses any amount of empty lines or comments as group delimiter as opposed to just comments.

**Comment by basile-henry** [comment]
The pragmas could only be sorted by groups split using comments as delimiters.

This is similar to what `stylish-haskell` does with imports (and maybe also language pragmas) as far as I remember. Though it uses any amount of empty lines or comments as group delimiter as opposed to just comments.

**Comment by mrkkrp** [comment]
I don't see a good way to implement it. What we currently do is we check every comment to detect those that are language pragmas. Keeping track of comments between pragmas would require more state. Seems to be quite troublesome for little benefit. I'm keeping this one with low priority.

**Comment by recursion-ninja** [comment]
There are semantic problems with this approach. Some language extensions enable other language extensions implicitly. If you want to disable them, you must specify that after the extension that implicitly enables them is specified.

Consider this input:
```
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeFamilies    #-}

{-# LANGUAGE NoMonoLocalBinds    #-}

module Foo (
  , bar
  ) where
```
This module will *not* have `MonoLocalBinds` enabled becaue the `NoMonoLocalBinds` language extension occurs after the `TypeFamilies` language pragma which implicitly enables `MonoLocalBinds`.

If the styler groups the language extensions and alphabetizes them like so, there will be problems: 
```
{-# LANGUAGE NoMonoLocalBinds    #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeFamilies    #-}

module Foo (
  , bar
  ) where
```
Because `NoMonoLocalBinds` appears before `Typefamilies`, GHC considers it "disabled." GHC then continues to fold over the list of language extensions and when it encounters `TypeFamilies`, `MonoLocalBinds` is implicitly enabled.

This grouping and alphabetizing of language extensions will cause semantic difference in the input and output modules. This is the reason `stylish-haskell` does not do this.

**Comment by mboes** [comment]
In light of this, perhaps we should reorder only inside groups separated by a newline.

**Comment by neongreen** [comment]
It seems like "don't reorder extensions at all" is safer. Or perhaps we
should put all "NoX" extensions into their own group at the end?

**Comment by neongreen** [comment]
Though frankly, it's not worth losing the "if it compiled before
formatting, it will still compile after formatting" invariant for such a
minor benefit (sorted pragmas).

**Comment by recursion-ninja** [comment]
The problem, is that a list of language extensions is not *always* a list of commutative elements, however the list often is and users will likely expect the alphabetized behavior when this is the case.

If one were to take care to note which language extensions were implied by which other ones, you determine which elements in the list of language extensions could not be commuted "past" one another when alphabetizing. If this bookkeepping was performed, you could indempotently output a *mostly* alphabetized list of language extensions when one or more elements cannot commute "past" each other or a completely alphabetized list when all elements can be commuted. 

While this approach would require much more work to implement and maintain, it is the most correct option for an opinionated code styler.

**Comment by mrkkrp** [comment]
I agree we should not abandon sorting, we just should make it more clever.

**Comment by mrkkrp** [comment]
@recursion-ninja Now there is a separate issue about sorting: #404. I think it's a different problem.

**Comment by lrworth** [comment]
Just noting that the same goes for

```
-- Avoid warning produced by TH.
{-# OPTIONS_GHC -fno-warn-overlapping-patterns #-}
```
