### ISSUE TITLE
Empty 'where' is removed, leading to spurious sanity check failure

### ISSUE THREAD

**Issue by neongreen** [tweag/ormolu#224]
Input:

```haskell
foo = id
  where
```

Output:

```haskell
foo = id
```

```
AST of input and AST of formatted code differ.
  at <stdin>:(1,1)-(2,7)
Please, consider reporting the bug.
```

**Comment by neongreen** [comment]
This affects [beam](github.com/tathougies/beam/).

**Comment by neongreen** [comment]
> good first issue

Should this issue be fixed by leaving empty `where`s in place, or by modifying the AST check?

**Comment by drathier** [comment]
Does empty `where` have a semantic difference relative to not having the `where` at all? If not, I think we should remove it.

**Comment by neongreen** [comment]
Generally it doesn't, but if it's inside `[d| ... |]`, it does because I can inspect the AST with Template Haskell and do whatever I want with the results.

If this was my project, I'd say "let's not modify AST unless there's a good reason to".

**Comment by mrkkrp** [comment]
We should not modify AST in anyway. Empty `where` should be preserved as is.
