### ISSUE TITLE
BlockArguments gets formatted in an unpleasing way

### ISSUE THREAD

**Issue by mitchellwrosen** [tweag/ormolu#241]
```haskell
foo do
  bar
```
is currently formatted as
```haskell
foo
  do
    bar
```
Is that intentional? Thanks.

**Comment by mrkkrp** [comment]
Is this the same as

```haskell
foo $ do
  bar
```

semantically?

**Comment by mboes** [comment]
yes.

**Comment by aspiwack** [comment]
As far as I'm aware, though, the input is only legal with [`-XBlockArgument`](https://ghc-proposals.readthedocs.io/en/latest/proposals/0010-block-arguments.html).
