### ISSUE TITLE
Detect if semicolon syntax is used and error-out immediately

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#253]
We may eventually support semicolon syntax, however not in the first release. I propose we error out if the syntax is even used. Reasons:

* It's better for the image of the project if Ormolu errors out clearly explaining why instead of just failing with non-obvious messages which could make users think that the tool is unreliable.
* It's easier to spot remaining issues if we filter out semicolon-induced ones for now, for example when trying the tool on packages from Hackage.

**Comment by mboes** [comment]
Explicit braces and semi colons is a matter of style. Therefore, since Ormolu is a tool to normalize style, we should pick one `do`-block style and use that style everywhere. If the semi-colons are hard to strip out for some reason (is it?), it's fair to at least error out as a first step.

**Comment by mrkkrp** [comment]
> hard to strip out

The problem is that they are not part of AST, and only available in annotations. Furthermore, I imagine that spans of all sub-expressions end up on the same line and that messes with how things work. I did not look in details. It may be that it's feasible to support semicolons (and by that I mean essentially stripping them).

One fact is clear: they cause a lot of failures where "ordinary" syntax in input files works very well now. To make the first release faster we could temporarily skip supporting the feature for now.

**Comment by mrkkrp** [comment]
Perhaps we also should add a section about currently limitations.

**Comment by mrkkrp** [comment]
We decided to try to support semicolons in the first release, so this is not necessary.
