### ISSUE TITLE
SPECIALIZE INLINE pragma is formatted incorrectly

### ISSUE THREAD

**Issue by utdemir** [tweag/ormolu#277]
Discovered in `Agda` codebase:

Before: 

```
{-# SPECIALIZE INLINE mapTCMT :: () #-}
```

After (with `--unsafe`):

```
{-# SPECIALIZE mapTCMT :: () #-}
```

Which causes input and output AST's to differ.

**Comment by mrkkrp** [comment]
I believe this is fixed in #286.
