### ISSUE TITLE
What is the policy for `if-then-else` clause?

### ISSUE THREAD

**Issue by cblp** [tweag/ormolu#299]
This looks ugly:

```haskell
do
  action before
  if condition
  then action 1
  else action 2
  action after
```

Is it intended?

**Comment by cblp** [comment]
In real code, I've seen two styles:
```haskell
do
  action before
  if condition
    then action 1
    else action 2
  action after
```
and
```haskell
do
  action before
  if condition then
    action 1
  else
    action 2
  action after

```

**Comment by mrkkrp** [comment]
I myself align `then` and `else` one level to the right, however I think @mboes and @aspiwack had some argumentation for the current design, so I invite them to recite it here.

**Comment by mrkkrp** [comment]
I'd like to change it to give a bump to `then` and `else` myself, because I agree that the current formatting is ugly.

**Comment by aspiwack** [comment]
I don't use if-then-else in do-blocks, personally (I use `case` systematically). So, no opinion in that context.

Outside of do-block, this problem doesn't occur, so an extra indentation of `then` and `else` is purely gratuitous, and I don't think that we should have gratuitous indentations.

I believe that was all the argument I have. Or had.

**Comment by mrkkrp** [comment]
I think we should do whatever makes it easier to read and be unconditional about formatting inside/outside so-blocks.

**Comment by cblp** [comment]
@aspiwack in this context, is "gratuitous" bad or good? Should we avoid or pursue it?

**Comment by cblp** [comment]
Variant B has some advantages:
1. It works as well in the pure expression syntax context.
2. Looks like if-statement in other languages.
3. Offers exactly 1 indentation level for 1 logical level.

So, we can have one style for all purposes.
