### ISSUE TITLE
What is the policy for odd (2k+1) indentation?

### ISSUE THREAD

**Issue by cblp** [tweag/ormolu#300]
MultiWayIf is formatted such way:
```haskell
if | condition -> _
   | condition -> _ -- 3 spaces
   | condition ->
     continuation -- 5 spaces
       and_so_on -- 7 spaces
```

Is it intended?

**Comment by mrkkrp** [comment]
What in your opinion is surprising about this formatting?

**Comment by cblp** [comment]
Text editors rely on indentation that is multiple of some value. For example, 2. That is how this code looks like in VSCode:
![1](https://user-images.githubusercontent.com/63495/63101525-dfec4300-bf81-11e9-8822-804ab2b151b9.png)
Guidelines don't follow the code blocks.
Also, operations "increase indent" and "decrease indent" move code to a nearest "tabstop", i.e. a position multiple of 2. And while Ormolu isn't perfect I have to use these operations.

**Comment by cblp** [comment]
If the rule of 2 spaces isn't a law in Ormolu, then why newline after `do`?
```haskell
do
  action
  action
```
when you can
```haskell
do action
   action
```

**Comment by mrkkrp** [comment]
> If the rule of 2 spaces isn't a law in Ormolu, then why newline after `do`?

This is mostly to hang `do`s and put the rest on the new line I think.

I don't see anything wrong with moving to nearest multiple of 2. Do you want to attempt to implement this change and see how it goes?

**Comment by cblp** [comment]
What do you prefer?
```hs
if  | _
    | _
```
or?
```hs
if| _
  | _
```
or?
```hs
if
  | _
  | _
```

**Comment by mrkkrp** [comment]
I think A and B are certainly too ugly. Either more than 1 space or no space is not nice.
