### ISSUE TITLE
ParallelListComp

### ISSUE THREAD

**Issue by cblp** [tweag/ormolu#301]
A parallel list comprehension is styled this way:

```haskell
{-# LANGUAGE ParallelListComp #-}

[ a
  | x <- xs,
    predicate x,
    let x' = f x
    | y <- ys,
      predicate y,
      let y' = f y
    | z <- zs,
      predicate z,
      let z' = f z
  ]
```

as if `y` and `z` are descendants of `x`. But no, they are parallel, and must look like siblings:

```haskell
[ a
  | x <- xs,
    predicate x,
    let x' = f x
  | y <- ys,
    predicate y,
    let y' = f y
  | z <- zs,
    predicate z,
    let z' = f z
  ]
```

Bug?

**Comment by mrkkrp** [comment]
Do you want to try to fix it?

**Comment by cblp** [comment]
I don't know where to start. Give me some pointers.

**Comment by yumiova** [comment]
Alternatively, I could take care of it, since I wrote the code to begin with.

**Comment by yumiova** [comment]
Removing the `sitcc` at line 551 seems to solve the problem. I could send a pull request containing that trivial change, or if that solution seems hacky somehow, I could try to make some further changes that feels more intuitively right.

**Comment by mrkkrp** [comment]
@yuminova Please go ahead :)
