### ISSUE TITLE
Detect headers in comments and add a newline after them

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#336]
This one is more experimental. Sometime there are headers like this:

```haskell
----------------------------------------------------------------------------
-- Helpers

foo :: Int -> Int
```

The blank line between the header and `foo` is currently erased. It would be good to somehow detect the header and make sure there is a newline after it so it doesn't get glued together with the next definition.

**Comment by neongreen** [comment]
Just in case, there's another common header style:

```haskell
----------------------------------------------------------------------------
-- Helpers
----------------------------------------------------------------------------
```

**Comment by neongreen** [comment]
Why 20? I've seen headers in the wild that started with 16 dashes or something.

**Comment by mrkkrp** [comment]
20 looked like a good number. So should it be 16 or maybe 8?

**Comment by neongreen** [comment]
I grepped Hackage and found blocks with 3 dashes, blocks with 5 dashes, etc.

I also found 3 dashes used as a delimiter between blocks of code.

I think 3 is good.

https://codesearch.aelve.com/haskell/search?query=%5E+*-%7B3,8%7D$&insensitive=off&space=off&precise=off&sources=on&page=1
