### ISSUE TITLE
Idempotence bug involving moving comments

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#340]
From formatting `parsec3`:

Original input:

```haskell
mergeErrorReply :: ParseError -> Reply s u a -> Reply s u a
mergeErrorReply err1 reply -- XXX where to put it?
    = case reply of
        Ok x state err2 -> Ok x state (mergeError err1 err2)
        Error err2      -> Error (mergeError err1 err2)
```

1 pass:

```haskell
mergeErrorReply :: ParseError -> Reply s u a -> Reply s u a
mergeErrorReply err1 reply = -- XXX where to put it?
  case reply of
    Ok x state err2 -> Ok x state (mergeError err1 err2)
    Error err2 -> Error (mergeError err1 err2)
```

2 pass (fixpoint):

```haskell
mergeErrorReply :: ParseError -> Reply s u a -> Reply s u a
mergeErrorReply err1 reply =
  -- XXX where to put it?
  case reply of
    Ok x state err2 -> Ok x state (mergeError err1 err2)
    Error err2 -> Error (mergeError err1 err2)
```

**Comment by mrkkrp** [comment]
This is actually pretty strange. My mental model is that in all cases the comment should be attached to `reply` and so it always should stay on the same line.

**Comment by utdemir** [comment]
Here is a smaller version:

```haskell
foo reply -- XXX
  = foo
```

What happens is that when we are deciding whether a comment follows an element, one of the predicates we use is `noEltBetween`, which checks if the comment follows an element by checking whether the next element starts after the end of the comment. However, in this example, the next element is `= foo`, and after the first pass we move the `=` before the comment, so the predicate fails to attach the comment to the same element on the next run.

Similar issues also occur on almost everywhere we move something to a line above. Some examples I made up:

```haskell
foo = \case
  True -- foo
    -> False
  False -> True
```

```haskell
foo
  :: () -- bar
  = foo
```

```haskell
a = b $ -- foo
  do
  foo
```

```haskell
foo =
  let a -- foo
        = b
   in c
```
