### ISSUE TITLE
Infix pattern synonym: ghc panic

### ISSUE THREAD

**Issue by guibou** [tweag/ormolu#355]
The following:

```haskell
{-# LANGUAGE PatternSynonyms #-}

pattern a :< b = (a, b)
```

Leads to ormolu crash:

```
ormolu: panic! (the 'impossible' happened)
  (GHC version 8.6.5 for x86_64-unknown-linux):
	not implemented yet: InfixCon
CallStack (from HasCallStack):
  error, called at src/Ormolu/Utils.hs:31:22 in ormolu-0.0.1.0-KdSq2D84oCzHMfc2HHokyf:Ormolu.Utils

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
```

I'm using ormolu 10232b9 which is master at the time of redacting this issue.

**Comment by utdemir** [comment]
Besides supporting infix pattern synonyms, another issue is reporting that as a GHC bug. I thought we had some piece of code to prevent that, I will try to figure out why it didn't work.

**Comment by mrkkrp** [comment]
Why should it be reported as a GHC bug though? It’s from working valid core AFAIK.

**Comment by utdemir** [comment]
@mrkkrp Turns out it was just a laziness issue causing the exception to be thrown inside GHC's parser when we check whether the AST differs after formatting.
