### ISSUE TITLE
Idempotence issue with an idiosyncratic per-argument Haddock

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#364]
Here is an example extracted from `brick` (enable it for CI testing once this is fixed):

```haskell
foo :: Int {- ^ start index -} -> Int {- ^ length -} -> t a -> t a
```

On first pass this results in:

```haskell
foo :: Int -> Int -> t a -> t a {- ^ start index -}
  {- ^ length -}
```

On the second pass the result is:

```haskell
foo :: Int -> Int -> t a -> t a {- ^ start index -}
    {- ^ length -}
```

And this is the fixpoint.

The style is not widely used, in fact it is the first time I see it, so maybe the fact that we move the comments like this is forgiveable, given how well our heuristics work in other (standard) cases. The idempotence issue should be fixed though.

**Comment by aspiwack** [comment]
Moving the comment like this changes the Haddock output, by the way. It's not only an idempotence bug.

I'm guessing it doesn't happen in the more common formatting

```haskell
foo
  :: Int -- ^ Start index
  -> Int -- ^ length
  -> t a
  -> t a
```

**Comment by mrkkrp** [comment]
I think actually that we could output following comment immediately instead of waiting till we output a newline when the comment is in multiline style.
