### ISSUE TITLE
Ormolu produces invalid syntax when using operators as record fields

### ISSUE THREAD

**Issue by utdemir** [tweag/ormolu#383]
Original:

```haskell
foo = Foo { (+) = 3 }
bar = foo { (+) = 4 }
```

After Ormolu (with `--unsafe`)

```haskell
foo = Foo {+ = 3}

bar = foo {+ = 4}
```

Where the parentheses around `+` is removed causing a syntax error,

Found when formatting `linear-base`.

**Comment by mrkkrp** [comment]
TBH, I did not know this is even possible!
