### ISSUE TITLE
Align opening and closing parentheses in multi-line layouts

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#388]
Some people find this style:

```haskell
( foo,
  bar
  )
```

...weird. Why would they think so...

Here is what we want to have in most cases:

```haskell
( foo,
  bar
)
```

...while still shifting the closing parentheses when absolutely necessary.

The change should apply to all similar constructs.

**Comment by pwm** [comment]
Huge +1 on this, ideally for all types of brackets.
