### ISSUE TITLE
Add to Stackage

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#412]
We should add the package to Stackage so that:

1. It benefits from Stackage reports when dependency boundaries should be updated.
2. People can use it easier with Stack.

Prerequisites: #344 (because Stackage nightly is now on GHC 8.8.1).

**Comment by Sir4ur0n** [comment]
I wanted to point out that integration into Intellij-Haskell requires Ormolu to be available on Stackage, see https://github.com/rikvdkleij/intellij-haskell/issues/485

**Comment by mrkkrp** [comment]
Need `nixpkgs` to have GHC 8.8.1 as the default GHC version so we can switch to that on CI. I haven't checked that for a while though.

**Comment by mrkkrp** [comment]
Or perhaps we need to support at least two versions of GHC at the same time to make things more smooth here. (Hear this @aspiwack !)

**Comment by mrkkrp** [comment]
Ormolu is now on Stackage.
