### ISSUE TITLE
Parsing error on comments

### ISSUE THREAD

**Issue by stoeffel** [tweag/ormolu#413]
I'm getting a parsing error with comment that have a `|` like `-- |` if they are between `module` and the first `import.

```
ormolu src/Lib.hs
Parsing of source code failed:
  src/Lib.hs:4:1-6
  parse error on input ‘import’
```

## sscce

```hs
module Lib (someFunc) where

-- | Foo
import Prelude
```
and
```hs
module Lib (someFunc) where

{-| Foo -}
import Prelude
```

Thanks for your awesome work!

**Comment by mrkkrp** [comment]
Input files should be parsable by Haddock. I don't think you can attach `-- |` haddock to an import.

**Comment by stoeffel** [comment]
Oh, got it! That makes sense. 
Thanks!
