### ISSUE TITLE
Remove duplication in imports

### ISSUE THREAD

**Issue by tseenshe** [tweag/ormolu#414]
It would be very useful if ormolu were to de-dupe import sections such as

```haskell
import Data.List (nub)
import Data.List (nubBy)
```

into

```haskell
import Data.List (nub, nubBy)
```

This would reduce the burden on tools that add imports such as [`haskell-tng-import-symbol-at-point`](https://gitlab.com/tseenshe/haskell-tng.el/blob/4e2cf006eb8c544ace8aafd2e8375dcb31dd8c8e/haskell-tng-util.el#L73-89)

**Comment by mrkkrp** [comment]
I don’t have anything against it, but realistically it’s going to be a pretty low-priority target.
