### ISSUE TITLE
Broken link in Hackage README

### ISSUE THREAD

**Issue by david-christiansen** [tweag/ormolu#416]
On [Hackage](https://hackage.haskell.org/package/ormolu), at least at the time of writing, there is a link with the text "the design document" that points at https://hackage.haskell.org/package/ormolu-0.0.1.0/ormolu-0.0.1.0/src./DESIGN.md#cpp . This gives a 404.

**Comment by mrkkrp** [comment]
The readme is meant to be read on GitHub, not on Hackage. Hackage just tries to render readme files as a courtesy but it 1) cannot do it properly for things like tables 2) will not get links to contents to the repo right.

We could make all links absolute, although this is somewhat ugly.

**Comment by mboes** [comment]
Better to avoid users' surprise than to be ever so slightly technically more elegant. If the README is redistributed on other platforms independently of other documents, then including absolute references is the right thing to do.

**Comment by david-christiansen** [comment]
Thanks for looking at it!

**Comment by mrkkrp** [comment]
Resolved in f83f6fd.

**Comment by david-christiansen** [comment]
That was quick! Thanks!
