### ISSUE TITLE
Use ghc-lib-parser instead of GHC

### ISSUE THREAD

**Issue by neongreen** [tweag/ormolu#422]
This would let us have features from GHC 8.8.1 while still using GHC 8.6.5 from Nixpkgs.

I can make a patch.

**Comment by neongreen** [comment]
Bonus: Ormolu will be compilable with GHCJS.

**Comment by mboes** [comment]
@mrkkrp decoupling Ormolu from the version of GHC that the user happens to use would be a win. Currently, if you and I compile the exact same version of Ormolu, reformatting a file with the resulting binary might fail for me but succeed for you. @neongreen's proposal fixes that.

**Comment by mrkkrp** [comment]
My concern is longevity of this `ghc-lib-parser` project. What if something happens to Digital Assert? Vanilla `ghc` will always be there.

**Comment by mboes** [comment]
That's a pretty theoretical concern. The porting work isn't difficult so worse comes to worse we revert (that won't make a difference to the user).

**Comment by mrkkrp** [comment]
OK, @neongreen please go ahead with the PR.
