### ISSUE TITLE
Apply consistent layout to type constructors in signatures

### ISSUE THREAD

**Issue by neongreen** [tweag/ormolu#427]
Input:

```haskell
f :: forall x y.
      D x y x y
```

Output:

```haskell
f ::
  forall x y.
  D x y x
    y
```

---

While I'm at it, this should also probably be consistent with data declarations?

Input:

```haskell
data D = forall x y.
         D x y x y
```

Output:

```haskell
data D
  = forall x y.
    D
      x
      y
      x
      y
```

---

My preferred option in both cases would be:

```haskell
f ::
  forall x y.
  D x y x y

data D
  = forall x y.
    D x y x y
```

**Comment by mrkkrp** [comment]
What do you mean "while I'm at it"? If you are referring to your current work on #423, then please introduce as few changes as possible and then when it's merged we can return to this one and do it in a separate PR.

Otherwise, yes, I agree that these changes make sense.

**Comment by neongreen** [comment]
"while I'm at it" means "while I'm talking about things that have `D x y x y` in them". Sorry for confusing you.

I'm not going to make this change in #423.
