### ISSUE TITLE
Don't remove empty foralls

### ISSUE THREAD

**Issue by neongreen** [tweag/ormolu#429]
I've learned that removing empty foralls is not always semantically correct: https://github.com/Ericson2314/ghc-proposals/blob/no-implicit-forall/proposals/0000-no-implicit-forall.rst#3examples. This is minor, but I think we should add a regression test for this.

**Comment by mrkkrp** [comment]
I'd be surprised to learn that we remove empty `forall`s. Feel free to add a test for this though.

**Comment by mrkkrp** [comment]
Hmm, we actually seem to remove empty `forall`s.
