### ISSUE TITLE
File header comments get moved into export list

### ISSUE THREAD

**Issue by cdsmith** [tweag/ormolu#430]
Ormolu 0.0.1 (latest Hackage release) turns this:

```
{-
    Copyright blah blah blah
-}

-- | My favorite module
module Test (foo) where

foo = 42
```

Into this:

```
-- | My favorite module
module Test
  ( {-
        Copyright blah blah blah
    -}

    foo,
  )
where

foo = 42
```

This must be a bug, right?  Strangely, it doesn't happen if there's no haddock comment on the module.

**Comment by basile-henry** [comment]
This is definitely a weird behaviour and we should have a closer look at it.

Just a side note, you should be able to put the Copyright and other information about the module straight into the Haddock module description:
https://www.haskell.org/haddock/doc/html/ch03s03.html

**Comment by mrkkrp** [comment]
This is now fixed.

**Comment by cdsmith** [comment]
Thanks!  Looking forward to the hackage release.

I realize Haskell has some of its own conventions about how to include licensing info.  In my case, I'm working with lawyers who have differing opinions, and the means to enforce them!  I don't want paragraphs of legal text about the source to make it into generated documentation for every module, so this requires a separate non-haddock comment before the module comment.
