### ISSUE TITLE
Haddocks are floating into function signatures when they shouldn't be

### ISSUE THREAD

**Issue by neongreen** [tweag/ormolu#440]
Input:

```haskell
module Main where

-- | This is 'f'

--     * Comment
f :: a -> b
```

Output:

```haskell
module Main where

-- | This is 'f'
f ::
  --     * Comment
  a -> b
```

**Comment by mrkkrp** [comment]
The input is a bit pathological, right? The haddock ends up not being associated with the function in the original snippet, right?

**Comment by neongreen** [comment]
> The haddock ends up not being associated with the function in the original snippet, right?

Right.
