### ISSUE TITLE
Parse error on import of pattern.

### ISSUE THREAD

**Issue by philderbeast** [tweag/ormolu#441]
I tried out this code [snippet](https://github.com/BlockScope/flare-timing/blob/df368526ad78c7d13f15a9290c9dc35b334b6559/gap/library/Flight/Gap/Validity.hs#L37) on [ormolu commit 2517d98, ormolu-live commit 9ee83a4](https://monadfix.com/ormolu/) and got a parse error.

```haskell
import Flight.Ratio (pattern (:%))
```

```
Parsing of source code failed:
  <input>:1:31-32
  parse error on input `:%'
```

**Comment by neongreen** [comment]
It works fine if you enable `{-# LANGUAGE PatternSynonyms #-}`.

Unfortunately, we can't enable PatternSynonyms by default because it steals syntax. I wonder if there is an extension that lets GHC understand `pattern` in imports without enabling it everywhere else, though.

**Comment by philderbeast** [comment]
Indeed, the ormolu live snippet works with the language pragma added.

```haskell
{-# LANGUAGE PatternSynonyms #-}
import Flight.Ratio (pattern (:%))
```

**Comment by blackgnezdo** [comment]
Is there any chance ormolu can grow a set of command line flags for enabling language options? That would make region formatting more practical. The case I have in mind is gradual adoption where  I only format a selected region in the editor (e.g. just the imports and not pragmas at the top).

**Comment by mrkkrp** [comment]
`--ghc-opt` already allows you to enable language options. Please see output of `ormolu --help`.
