### ISSUE TITLE
Invalid formatting of Haddocks for data type fields

### ISSUE THREAD

**Issue by judah** [tweag/ormolu#445]
From this input:

```
data X
  = B
     !Int -- ^ y
     C
```

Ormolu generates:

```
data X
  = B
      !-- | y
      Int
      C
```

which results in a parsing error:

```
Parsing of formatted code failed:
  <input><rendered>:(2,5)-(3,9)
  Cannot parse an infix data constructor in a data/newtype declaration:
  B !--
Please, consider reporting the bug.
```

Reproduced with Ormolu commit 2517d98.

**Comment by mrkkrp** [comment]
In https://github.com/tweag/ormolu/tree/mk/fix-445 I made it render like this:

```haskell
data X
  = B
      -- | y
      !Int
      C
```

But this is rejected by the parser! Looks like a bug upstream to me.

**Comment by mrkkrp** [comment]
Opened GHC issue: https://gitlab.haskell.org/ghc/ghc/issues/17652.

**Comment by mrkkrp** [comment]
Related (almost the same issue): #428.

**Comment by m00ngoose** [comment]
also bumped into this
