### ISSUE TITLE
Invalid formatting with type synonym and comment

### ISSUE THREAD

**Issue by judah** [tweag/ormolu#448]
Input:

```
module M where

-- | A

-- B
type D = E
```

Output:

```
module M where

-- | A
type -- B
D = E
```

Error:
```
Parsing of formatted code failed:
  <input><rendered>:5:1
  parse error (possibly incorrect indentation or mismatched brackets)
Please, consider reporting the bug.
```

And with `data`, it's indented correctly:

```
module M where

-- | A
data -- B
  D = E
```

**Comment by mrkkrp** [comment]
This is another form of the same problem as #440.

**Comment by mrkkrp** [comment]
Just to be clear: the Haddock `-- | A` is probably not associated with the `type` declaration, so there is a problem in the input. That said, it should be handled better.
