### ISSUE TITLE
Idempotence issue with operators

### ISSUE THREAD

**Issue by judah** [tweag/ormolu#451]
The following code leads to an idempotence error:

```
a =
  b & c .~ d
    & e %~ f
            g
```

Result:
```
Formatting is not idempotent:
  before: "  & e\n      %~ f\n   "
  after:  "  & e\n    %~ f\n     "
```

Additionally, indenting the `%~` to a different line than the `&` seems unnecessarily aggressive.  Furthermore, it results in `g` having less indentation than `f` in the output, when before it was indented further than `f`:

```
a =
  b & c .~ d
    & e
      %~ f
        g
```

**Comment by utdemir** [comment]
Thanks! I fixed the idempotency issue (see the PR).

As about the styling issues, Ormolu thinks `e %~ f g` is a multiline expression, and it formats it as one, putting the operator on a newline. Technically, we can have a special case when the LHS is single line and RHS is multi line; but it would cause us to have two different formatting styles and I am not sure if it is worth it.

You are right on `g` having less indentation than `f` is not ideal. We used to always indent the arguments more than the function itself, but later we changed that behavior; however I don't remember why. @mrkkrp Do you remember the reason of that change? To me it makes sense to use `sitcc` on the arguments.

**Comment by neongreen** [comment]
The reason is that if you indent g further than f, you will have indentation depending on the length (of the operator), which Ormolu generally tries to avoid.

**Comment by mrkkrp** [comment]
I'm inclined to close this one now because:

* The transformation is idempotent now.
* All other points are really artifacts of Oromlu's general formatting style which emerged mostly as a combination of heuristics and compromises. It is not clear that we should change those at this point.
