### ISSUE TITLE
subtraction vs negative numbers

### ISSUE THREAD

**Issue by symbiont-alexey-babkin** [tweag/ormolu#476]
`attemptsRemaining-1` gets reformatted as `attemptsRemaining -1` and not `attemptsRemaining - 1` as one would expect IMO.

**Comment by mrkkrp** [comment]
This is how GHC parser itself parses it, there is nothing we can do. If you add spaces around the minus sign they will be preserved though.

**Comment by symbiont-alexey-babkin** [comment]
thanks, yes I used the workaround you suggested, still it feels weird. Closing.
