### ISSUE TITLE
Parse error on a standalone declaration with an associated Haddock

### ISSUE THREAD

**Issue by DavSanchez** [tweag/ormolu#480]
Hello! I'm in the process of adding `ormolu` support to HIE, but I have doubts with the way `ormolu` seems to handle formatting just a selection inside a file, or if it's even advisable!

For the moment the local tests appear to be working when formatting the whole file on save. I'm testing with [the files that `ormolu` provides as examples](https://github.com/tweag/ormolu/tree/master/data/examples).

However, when trying to format just a segment of the whole file I get some errors, but they seem a bit erratical (in some segments the formatting works, in others doesn't, in others it seems to work but then trying to format the whole file fails, as the indentation was messed up in the process).

For example, let's try with the selection made in this file (please ignore the red wiggles):

![image](https://user-images.githubusercontent.com/11422515/70391332-eb99c480-19cb-11ea-90b9-0d5ef0825a25.png)

If I format the whole file it works without a problem. For the selection made, I think this would be the expected output:

![image](https://user-images.githubusercontent.com/11422515/70391371-619e2b80-19cc-11ea-9393-d4d040458ef2.png)

When trying with Format Selection, it complains the following (emphasis mine):

> [Error - 2:59:07 PM] Request textDocument/formatting failed.
  Message: ormoluCmd: **OrmoluParsingFailed (RealSrcSpan SrcSpanOneLine "/Users/David/Desktop/ormolu-tests/examples/declaration/class/associated-data2.hs" 16 5 9) "parse error on input `data'"**
  Code: -32603 

As said, if I select other segments it works, but sometimes it will break the indentation of the files, preventing the formatting of the whole file to work correctly after that.

As I think these errors have more to do with `ormolu` than with `HIE` I have opened the issue here. Maybe this is the expected behaviour and it is discouraged to try formatting file selections?

Thanks!

**Comment by mrkkrp** [comment]
It should be obivous that Ormolu has to work with Haddocks. Both Ormolu and the Haddock executable use GHC parser with a special setting to extract Haddocks. The thing is, though, that once this setting is activated, the input must form a finished Haskell module with correct Haddocks, otherwise it is a parse error. For some inexplicable reason though, if your module starts by a Haddock (as in your case here it starts with `-- | Baz baz`) it must have a module header to be a valid Haddock-ed module, otherwise it is a parse error.

So here you have it: Ormolu is not designed to work on regions. I guess there could be some hacking to do to make it work in most cases, but it's currently something you'll have to do in your code.

**Comment by DavSanchez** [comment]
Alright! Thanks a lot for clarifying.

**Comment by neongreen** [comment]
@DavSanchez Can you file a GHC issue?

**Comment by DavSanchez** [comment]
@neongreen I'll gladly open it in a few hours. However, at this point I don't know if I can provide much more information on the issue if I'm asked by the GHC team. If you have no problem with this (or are willing to lend me some help there) I'll open it and drop the link to it here.

**Comment by neongreen** [comment]
There isn't anything to provide besides "this piece of code doesn't parse in `ghc -haddock` mode":

```
$ cat /tmp/e.hs
-- | Foo
main = main

ghc -haddock /tmp/e.hs

/tmp/e.hs:2:1: error: parse error on input ‘main’
  |
2 | main = main
  | ^^^^
```

**Comment by neongreen** [comment]
Opened it myself: https://gitlab.haskell.org/ghc/ghc/issues/17561

**Comment by DavSanchez** [comment]
Ok! Thanks for opening it @neongreen, I was afk when you first responded.

If this GHC issue gets sorted out, could we expect being able to format code snippets without a problem, or we should take into account possible indentation breaks (for example, formatting just a segment of a function body that would remove preceding spaces/tabs)?

**Comment by neongreen** [comment]
Yes, extra indentation is removed. You should open a new feature request for this.

**Comment by neongreen** [comment]
The GHC issue already has a fix! That was quick. https://gitlab.haskell.org/ghc/ghc/merge_requests/2305

**Comment by DavSanchez** [comment]
From what I've seen they are not moving in the direction of the last link, so it will be some more time until the issue is actually fixed?

**Comment by neongreen** [comment]
Yeah, seems so.

**Comment by neongreen** [comment]
Fixed upstream: https://gitlab.haskell.org/ghc/ghc/-/issues/17561. Will probably be fixed in Ormolu when new ghc-lib-parser is out.
