### ISSUE TITLE
--ghc-opt always erroneously reports unrecognized options

### ISSUE THREAD

**Issue by Avi-D-coder** [tweag/ormolu#484]
This is related to #437 & #438.

```haskell
$ echo 'idString = id @String' | ormolu -o TypeApplications
```
```
The following GHC options were not recognized:
  TypeApplications
```

Removing `src/Ormolu/Parser.hs:208` gets rid of the error message, but ignores `TypeApplications`. Output: `idString = id@String`
```haskell
    case NE.nonEmpty leftovers of
      Nothing -> return ()
      Just unrecognizedOpts ->
        throwIO (OrmoluUnrecognizedOpts (unLoc <$> unrecognizedOpts))
```

**Comment by mrkkrp** [comment]
As you seem to have discovered by now, the problem is that GHC options for language extensions begin with the `-X` prefix, which is how you should provide them.
