### ISSUE TITLE
RecordDotSyntax support

### ISSUE THREAD

**Issue by Avi-D-coder** [tweag/ormolu#486]
Is it possible to add support for `expr.lbl` and `(.lbl)` in ormolu prior to `RecordDotSyntax` coming to GHC? Both forms are implemented in the [record-dot-preprocessor](https://github.com/ndmitchell/record-dot-preprocessor) and will be in GHC once `RecordDotSyntax` is implemented.

**Comment by neongreen** [comment]
Not before they land in the GHC parser.

**Comment by neongreen** [comment]
My understanding of the preprocessor is that it recognizes certain bits of
syntax and substitutes them with HasField methods. However, it does not
provide an extended version of the AST that would correspond to
Haskell+RecordDotSyntax. So we can't reuse the record-dot-preprocessor code
(much).

**Comment by Avi-D-coder** [comment]
I think I have a workable solution. I'll submit a PR latter today.

**Comment by Avi-D-coder** [comment]
It works I just have to pass `recDotPreOn`::`Bool` derived from DynFlags`src/Ormolu/Parser.hs` into `src/Ormolu/Printer/Meat/Declaration/Value.hs`. Is `R` the place to pass this info?
