### ISSUE TITLE
"AST of input and AST of formatted code differ" with MultiWayIf: a block-level 'if' applied to an expression

### ISSUE THREAD

**Issue by kvnflm** [tweag/ormolu#488]
Running ormolu (version 0.0.2.0) on the following code

```haskell
{-# LANGUAGE MultiWayIf #-}

if | p -> f
   | otherwise -> g
 x
```

produces the error
```
AST of input and AST of formatted code differ.
    at ormolu_test.hs:(3,1)-(5,2)
Please, consider reporting the bug.
```

**Comment by neongreen** [comment]
Furthermore:

```haskell
{-# LANGUAGE MultiWayIf #-}

(if | p -> f
    | otherwise -> g)
  x
```

```haskell
{-# LANGUAGE MultiWayIf #-}

( if
    | p -> f
    | otherwise -> g
)
  x
```

```
Parsing of formatted code failed:
  <input><rendered>:6:1
  parse error (possibly incorrect indentation or mismatched brackets)
Please, consider reporting the bug.
```

**Comment by neongreen** [comment]
I don't know if anybody would actually ever do such a thing, but it's not meaningless when interpreted as a top-level splice:

```haskell
{-# LANGUAGE TemplateHaskell #-}

(if genLenses 
   then makeLenses
   else const (pure []))
 ''X
```

**Comment by kvnflm** [comment]
`git bisect` suggests that this error started appearing with commit ee3c506889ae3396e76a9def6f9a85f40d1c5799.

**Comment by mrkkrp** [comment]
OK, this is an interesting one. Apparently if we want to keep the results of #307 and increment indentation by 2 (as we should) the only option is to increment indentation for this `x` argument by exactly 1. If we print `x` with indentation 0, it's not an argument of the if block. If we bump it by 2, it apparently becomes an argument of `g`, which also changes the meaning of the program. But if we want to use only increments of 2, then using 1-space indent is no-go. Difficult situation.

**Comment by mrkkrp** [comment]
@neongreen Note that your example works if it's not a top-level expression:

```haskell
baz =
  (if | p -> f
      | otherwise -> g)
    x
```

**Comment by mrkkrp** [comment]
I imagine one solution here could be: print multi-way if like this:

```haskell
baz =
  if  | p -> f
      | otherwise -> g
    x
```

**Comment by neongreen** [comment]
Looks good to me.
