### ISSUE TITLE
Option to get leading comma instead of trailing comma in lists, records

### ISSUE THREAD

**Issue by dandoh** [tweag/ormolu#497]
I'm more used to this:
![image](https://user-images.githubusercontent.com/10379980/72213725-8420e880-3526-11ea-949b-c018b31fc859.png)
Than:
![image](https://user-images.githubusercontent.com/10379980/72213738-c64a2a00-3526-11ea-8f4d-d735eeccbe84.png)

**Comment by mrkkrp** [comment]
Please take time to at least read the readme before opening issues. It says:

> Implementing one “true” formatting style which admits no configuration.

The reason for this style for commas is explained in a blog post here:

https://www.tweag.io/posts/2019-10-11-ormolu-first-release.html

**Comment by dandoh** [comment]
Makes sense. Thank you!
