### ISSUE TITLE
Record updates and record-dot-preprocessor

### ISSUE THREAD

**Issue by pkapustin** [tweag/ormolu#498]
The record update syntax in record-dot-preprocessor relies on the fact that in 
`expr{lbl = val}` the `{` cannot have whitespace before it, but ormolu inserts an extra space.
I think that the spacing around `{` in record updates should not be changed in the files that use record-dot-preprocessor.

**Comment by neongreen** [comment]
@Avi-D-coder can you take a look at this?

**Comment by Avi-D-coder** [comment]
Yep

**Comment by Avi-D-coder** [comment]
@pkapustin thanks for pointing this out.
Test case for this.

```haskell
data FooBar = FooBar {foo :: Int, bar :: Int} deriving (Show)

newtype Foo = Foo {foo :: Int} deriving (Show)

fooplus f n = f {foo = f.foo + n} -- Error: Record update is ambiguous
```
