### ISSUE TITLE
Implement rendering of rewrite rule declarations

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#51]
Extend `p_hsDecl` in `Ormolu.Printer.Meat.Declaration` to support rendering of rewrite rule declarations.

**Comment by mrkkrp** [comment]
Does anyone want to pick up this one? I imagine it's a relatively easy one.

**Comment by mrkkrp** [comment]
This is a relatively easy one. Does anyone want to pick this up or should I include it in my TODO list?

**Comment by PanAeon** [comment]
@mrkkrp I'll do it!
