### ISSUE TITLE
Allow Ormolu to format regions of code

### ISSUE THREAD

**Issue by judah** [tweag/ormolu#516]
It would be nice if Ormolu could be told to only change certain lines, and leave the rest unchanged.  This can help reduce the noise in individual code changes, when automated tooling applies the formatter only to the changed lines.

Even if it also needed to change some of the surrounding lines for consistency (e.g.: maybe an entire (sub)declaration?), it would still be useful versus always changing the whole file.

This item seems related to #435 (comments to disable formatting on a subset of the file).

**Comment by Avi-D-coder** [comment]
Both haskell-ide-engine and [haskell-language-server](https://github.com/haskell/haskell-language-server/) support range formatting with ormolu.

**Comment by judah** [comment]
Thanks @Avi-D-coder .  In both implementations I see this line:
https://github.com/haskell/haskell-ide-engine/blob/6dffe1352202a4fbf5a5b88927fdac0efed6c306/src/Haskell/Ide/Engine/Plugin/Ormolu.hs#L97
https://github.com/haskell/haskell-language-server/blob/80bc2e8fac470330479c9e2e2222ebf5a687b95f/src/Ide/Plugin/Ormolu.hs#L98
```You must format a whole block of code. Ormolu does not support arbitrary ranges.```

My intent with this ticket would be for Ormolu to handle "partial" block ranges better, either by only formatting them partially or else increasing the range to fully cover whole block(s).  I think it has more useful information internally since, after parsing, it knows exactly which lines belong to which `HsDecl`s (for example).

**Comment by Avi-D-coder** [comment]
That's going to be more tricky than my approach, through it would be nice.
Best of luck!

**Comment by fendor** [comment]
This is great! It will simplify the implementation in haskell-language-server!
