### ISSUE TITLE
Convenient default options

### ISSUE THREAD

**Issue by sir4ur0n** [tweag/ormolu#519]
Hi,

Is there some way to configure the default GHC options (like extensions) not enabled by default, like `XTypeApplications`? We really don't want to repeat the pragma in each of our file...

For the moment what we do in my team is:
```nix
# shell.nix
let
  # Wrap Ormolu to add our default extensions that are not enabled by default in Ormolu
  # Run 'ormolu --manual-exts' to find out which extensions are not enabled by default
  # Inspired by https://nixos.wiki/wiki/Nix_Cookbook
  # If for whatever reason you want to reformat the whole code base, run:
  # for f in ./**/*.hs; do
  #   ormolu --mode inplace "$f"
  # done
  ormolu-wrapped = symlinkJoin {
    name = "ormolu";
    paths = [ ormolu ];
    buildInputs = [ pkgs.makeWrapper ];
    postBuild = ''
     wrapProgram $out/bin/ormolu \
       --add-flags "\
         --ghc-opt -XBangPatterns \
         --ghc-opt -XTypeApplications \
       "
    '';
  };
in
  mkShell {
    buildInputs = [
        ormolu-wrapped
        # Other build inputs
    ];

  # Other conf, like env vars
  }
```

However:
* this feels hack-ish
* relies on Nix (+ don't forget to use `direnv` or run inside a nix-shell otherwise the code will be changed, cf https://github.com/tweag/ormolu/issues/452 Ormolu changes the code)
* it already seems that different people use different tricks (see https://github.com/tweag/ormolu/issues/517 where they use Perl parsing)

I feel like supporting an Ormolu configuration file at the root of the project would be an improvement for such a use case.

I am aware of:
* https://github.com/tweag/ormolu/pull/157 (YAML configuration file support removed) 
* https://github.com/tweag/ormolu/issues/517 to automagically discover default extensions from build files. What I'm asking is simpler: support default configuration in a dedicated Ormolu file

Thank you for Ormolu and cheers!

**Comment by seagreen** [comment]
I'm not sure this exists, but if there was something like https://editorconfig.org/ that allowed you to choose what executable + arguments to use to format any given file type that would be a nice general solution.

**Comment by seagreen** [comment]
Also see: https://github.com/tweag/ormolu/issues/452
