### ISSUE TITLE
Implement documentation and warning declarations

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#52]
Extend `p_hsDecl` in `Ormolu.Printer.Meat.Declaration` in order to support `WarningD` and `DocD` declarations. I'm not sure what is the role of `DocD` and if it's at all necessary given that we render all comments automatically. Perhaps it could be skipped.

**Comment by ruhatch** [comment]
I think `DocDecl`s will be removed in the future and only get parsed in `haddock` mode, so I'm not sure we need to support them.

**Comment by mrkkrp** [comment]
This seems to be fully-implemented now.
