### ISSUE TITLE
quasiquoter braces get misaligned

### ISSUE THREAD

**Issue by mheinzel** [tweag/ormolu#523]
```
foo = f $
  [quasiquoter|
    test
  |]
```

gets turned into

```
foo =
  f $
    [quasiquoter|
    test
  |]
```

which does not seem desirable to me, but not sure.

`ormolu 0.0.3.1 master 55d8b7f8c482655ea575425e55352e650f304ea0`,
`using ghc-lib-parser 8.8.2.20200205`

**Comment by mrkkrp** [comment]
The indentation level of `|]` is determined by the quoted string. If we change the indentation level we'll change the quoted string—something we cannot do.
