### ISSUE TITLE
Ormolu deletes comments from source code

### ISSUE THREAD

**Issue by kolree** [tweag/ormolu#524]
The original input:

```haskell
instance Foo Int where

  -- Here goes a comment.
  --
  --   something
  -- * something

  foo :: Int
  foo = 0
```

gets reformatted into:

```haskell
instance Foo Int where
  -- Here goes a comment.
  --
  --   something

  foo :: Int
  foo = 0
```

The part of the comment starting with `-- *` is lost.

**Comment by mrkkrp** [comment]
Please provide code snippets that show your original input and the result after formatting. I do not know how to make that site format the snippet (`Ctrl-I` does nothing for me) and the example probably can be minified.

**Comment by symbiont-eric-torreborre** [comment]
Here is another example:
```
function1 :: Int -> Text
function1 n =
  function2 n "***"
  where
    -- | this is function 2
    --   it calls show
    function2 n t = show n <> t
```
gets reformatted into
```
function1 :: Int -> Text
function1 n =
  function2 n "***"
  where
    function2 n t = show n <> t
```
The whole haddock-like section disappears

**Comment by mrkkrp** [comment]
That’s different, it’s #474.

**Comment by symbiont-eric-torreborre** [comment]
Thanks Mark.

**Comment by mrkkrp** [comment]
Apparently this is how GHC parser works. It picks up the lines that start with `-- *` and removes them.

**Comment by mrkkrp** [comment]
Essentially the same as #474.

**Comment by symbiont-eric-torreborre** [comment]
Let's close it as a duplicate then.
