### ISSUE TITLE
Support the new qualified import syntax

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#526]
As of GHC 8.10 it appears that a new form of import syntax is possible:

```haskell
import X qualified
```

Enabled by `ImportQualifiedPost`.

There are three options how to deal with it:

* Convert everything to the old style and delete the pragma. This follows the idea of making the output uniformly formatted.
* Convert everything to the new style. Not an option, because only the latest version of the compiler supports it and we'd need to add a pragma per file, which is probably not what is expected from a formatter.
* Format depending of whether the `ImportQualifiedPost` pragma is enabled. More work, but this should please everyone. So I'd say let's go with this one.

**Comment by utdemir** [comment]
Just to make the options complete; I guess another option would be to leaving it to the user. Looks like ghc-lib-parser exposes the required information. And one disadvantage of your preferred approach is that adding that language pragma will amplify the diffs by changing every qualified import. But I do not see a better solution, so I think we should still go ahead with your suggestion.

I am planning to implement this over the weekend, if no one else starts before me. I'm planning to implement it with two PR's where the first one updates ghc-lib-parser and the Nix code for GHC 8.10 and the second one actually implementing this change.

**Comment by mrkkrp** [comment]
> And one disadvantage of your preferred approach is that adding that language pragma will amplify the diffs by changing every qualified import.

That should not happen. If for a particular module the pragma is enabled, then all qualified imports in that module should be formatted in postfix fashion already. Neither "adding of language pragma" is necessary. All we have to do is to check if it's enabled and then format accordingly.
