### ISSUE TITLE
Possible to have pre-built binaries

### ISSUE THREAD

**Issue by joneshf** [tweag/ormolu#543]
# The situation

Building `ormolu` from source takes a long time (primarily due to `ghc-lib-parser`). In an unconstrained environment, this is an annoyance. In a constrained environment, this becomes an issue.

One example is if `ormolu` is being built on CI. It's possible to timeout building just `ormolu` (depending on the CI service). If there were binaries available for download, that ought to make using (and adopting) `ormolu` considerably easier. That's not the only example, but it's one that I run into often.

Some inspiration can be found with `hlint`. There are binaries to [pull down `hlint` directly](https://github.com/ndmitchell/hlint/releases/tag/v2.2.11), or a [script to run `hlint` automatically](https://github.com/ndmitchell/hlint#running-with-continuous-integration) (if you trust scripts off the internet). Not asking for this level of commitment. Pointing out some prior art.

# The ask

Is there any possibility we could get pre-built binaries available for download?

I'm not asking for a specific location on the internet, automation with CI, or any of that right now. The only thing I'm really looking for is at least one pre-built binary available for download (could be manually added to a release for all it matters to me). It would be ideal to have binaries for Linux, macOS, and Windows, but even just having one of the three would be a huge improvement or having to build from source.

If there are pre-built binaries available somewhere, could the documentation be a bit more explicit on where to find them? I didn't see anything that immediately popped out in the readme.

**Comment by joneshf** [comment]
Bump.

**Comment by mrkkrp** [comment]
We've seen your request.

**Comment by joneshf** [comment]
I'm sorry, I'm not sure how to interpret that response. Does that mean it won't happen? Does that mean it's in the works? Does that mean something else?

**Comment by joneshf** [comment]
Gotcha. Thanks for explaining!

**Comment by jkachmar** [comment]
Would y'all be open to accepting a PR that enables automating the process of building/releasing binaries in CI or something?

I'm using `ormolu` with Nix, which is arguably the most convenient way to add it to a project, and even then I'm not thrilled with the additional space it takes on my machine versus a plain binary.

**Comment by mrkkrp** [comment]
Perhaps just adding a Nix expression that builds a fully static Ormolu binary would be enough?

**Comment by joneshf** [comment]
As long as that's addressable _somehow_ on the internet without using nix explicitly, that would be enough for me.

**Comment by mboes** [comment]
Stack provides static binaries for convenience. It wouldn't be outrageous for Ormolu to do the same, for those people who are happy to run untrusted binary blobs from the internet on their system.

**Comment by utdemir** [comment]
I tried to compile a static Ormolu executable using `pkgsMusl` from Nix, however it seems like we're blocked on https://github.com/NixOS/nixpkgs/issues/85924.

**Comment by pjones** [comment]
I have a branch with a [`static.nix`](https://github.com/pjones/ormolu/blob/20d54ddccca3b2572dc4af4742693aa179122c35/static.nix) file that can build a static Linux executable.  Note that I needed to update the nixpkgs commit to the latest on `nixpkgs-unstable`.

While the package set used to build the static executable comes from the [`static-haskell-nix`](https://github.com/nh2/static-haskell-nix) project, I'm using [nix-hs](https://github.com/pjones/nix-hs/) since it can patch nixpkgs to work around the previously mentioned issue (NixOS/nixpkgs#85924).
