### ISSUE TITLE
ormolu --manual-exts panics

### ISSUE THREAD

**Issue by amesgen** [tweag/ormolu#544]
On `master`:
```
$ ormolu --manual-exts
ormolu: ormolu: panic! (the 'impossible' happened)
  (GHC version 8.10.1:
	v_unsafeGlobalDynFlags: settings not initialised

Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug
```

This panics in ghci: 
```haskell
showOutputable <$> manualExts
```

<hr>

Could be fixed by using `show` instead of `showOutputable` (see [here](https://hackage.haskell.org/package/ghc-lib-parser-8.10.1.20200324/docs/src/Outputable.html#line-906)), but this might not be future-proof.

**Comment by mrkkrp** [comment]
8.10.1 is not yet officially supported. I'll work on that tomorrow.

**Comment by amesgen** [comment]
For clarity: I used GHC 8.8.3 to compile ormolu. It says 8.10.1 because of ghc-lib-parser.

**Comment by mrkkrp** [comment]
Looks like a regression introduced by #531. cc @utdemir
