### ISSUE TITLE
Formatting of module header is different between when there is a module doc and when there isn't

### ISSUE THREAD

**Issue by jinwoo** [tweag/ormolu#561]
**Describe the bug**

A module header like this without a module doc,

```hs
module Main(main) where
...
```

remain as is after ormolu formats the file.

But if I add a module doc (haddock doc or just a comment), this code

```hs
-- | This is a module doc.
module Main(main) where
...
```

changes to

```hs
-- | This is a module doc.
module Main
  ( main,
  )
where
...
```

I'd like both to be formatted in the same way (I prefer the former).

**To Reproduce**

Use the two examples above.

**Expected behavior**

The formatting result should be the same whether there is a module doc or not.

**Environment**
 - OS name + version: Linux (Debian 5.2.17)
 - Version of the code:
```
ormolu 0.0.4.0 master dde756029115fdd98f326d698a433904598c63c5
using ghc-lib-parser 8.10.1.20200412
```

**Comment by mrkkrp** [comment]
This is caused by inclusion of the Haddock span into the span of module declaration itself (which I'd say is a bug in GHC). I knew about this one for a long time but sort of tolerated it. Let's try to fix it.

**Comment by jinwoo** [comment]
Thanks, Mark. As I said above, this happens even when the module doc is *not* a Haddock doc but merely a comment. Is it still caused by the Haddock span?

**Comment by mrkkrp** [comment]
This is what I remember. I haven't looked into this lately. Will need to check.
