### ISSUE TITLE
Not breaking long import lines

### ISSUE THREAD

**Issue by ncihnegn** [tweag/ormolu#567]
**Describe the bug**
Ormolu is not breaking long import lines.

**To Reproduce**
```import LLVM.AST (Definition (GlobalDefinition), Module, defaultModule, functionDefaults, moduleDefinitions, moduleName, noFastMathFlags)```

**Expected behavior**
Breaking the long lines to respect 80 char line length limit

**Environment**
 - macOS 10.15.4
 - ormolu 0.0.3.1

**Additional context**

**Comment by mboes** [comment]
This is by design. See the README and the DESIGN.md document. If you write the import on a single line, Ormolu will leave it that way. If you want it on multiple lines, give Ormolu an input where the import spans at least two lines.

**Comment by mrkkrp** [comment]
In general, there is no such thing as line length limit in Ormolu.
