### ISSUE TITLE
Parse error for `v = 1 -- $`

### ISSUE THREAD

**Issue by TristanCacqueray** [tweag/ormolu#594]
**Describe the bug**

This expression `v = 1 -- $` fails with:

```
The GHC parser (in Haddock mode) failed:
  <stdin>:1:7-10
  parse error on input `-- $'
```

**To Reproduce**

Run

```shell
ormolu <<< 'v = 1 -- $'
```

**Expected behavior**

This should not yield an error.

**Environment**
 - OS name: Linux
 - Version of the code: Ormolu master (`1fb65a218ce9baa0516717b42e7f50f83fc01b89`) built `using ghc-lib-parser 8.10.1.20200412`

**Comment by mrkkrp** [comment]
GHC parser fails, that’s it. Nothing we can do. We need to run the parser in Haddock mode which is a bit more picky then running it without Haddocks. Try generating docs from your code you’ll get the same error.
