### ISSUE TITLE
Ormolu doesn't build on MacOS Catalina

### ISSUE THREAD

**Issue by voidus** [tweag/ormolu#596]
**Describe the bug**
There is an error about path case (which I don't think breaks the build) and a CPP-related one (which I think is the problem). This might as well be a ghc+macos issue, but I don't know how to diagnose this.

The error messages are:

```
Building executable 'ormolu' for ormolu-0.0.5.0..

<built-in>:16:10: error:
     error: non-portable path to file '"dist/build/Ormolu/autogen/cabal_macros.h"'; specified path differs in case from file name on disk [-Werror,-Wnonportable-include-path]
#include "dist/build/ormolu/autogen/cabal_macros.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         "dist/build/Ormolu/autogen/cabal_macros.h"
1 error generated.

<built-in>:16:10: error:
     error: non-portable path to file '"dist/build/Ormolu/autogen/cabal_macros.h"'; specified path differs in case from file name on disk [-Werror,-Wnonportable-include-path]
#include "dist/build/ormolu/autogen/cabal_macros.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         "dist/build/Ormolu/autogen/cabal_macros.h"
1 error generated.

app/Main.hs:1:1: error:
    `cc' failed in phase `C pre-processor'. (Exit code: 1)
  |
1 | {-# LANGUAGE CPP #-}
  | ^

dist/build/ormolu/autogen/Paths_ormolu.hs:1:1: error:
    `cc' failed in phase `C pre-processor'. (Exit code: 1)
  |
1 | {-# LANGUAGE CPP #-}
  | ^

builder for '/nix/store/dgj7lm0gmqpc139yrhljq92mx5lw6pjv-ormolu-0.0.5.0.drv' failed with exit code 1
```

Full log attached:  [buildlog.txt](https://github.com/tweag/ormolu/files/4667591/buildlog.txt)

**To Reproduce**
```
git clone https://github.com/tweag/ormolu
cd ormolu
nix-build -A ormolu
```

**Expected behavior**
Successful build

**Environment**
 - MacOS Catalina 10.15.4
- `git show | head -5`
```
commit 1fb65a218ce9baa0516717b42e7f50f83fc01b89
Author: Mark Karpov <markkarpov92@gmail.com>
Date:   Thu May 14 17:15:15 2020 +0200

    Fix non-idempotent transformation of partly documented data definition
```

**Additional context**
I strongly suspect this is related to the system cc, since I cannot even build old versions (sampled a few back up to september). Any guidance on how to debug would be appreciated.

**Comment by voidus** [comment]
If anybody is more knowledgeable about ghc and stuff, I would be willing to pair on debugging this.

**Comment by lrworth** [comment]
This looks the same as https://github.com/tweag/ormolu/issues/470, but the workaround there assumes you're building ormolu with `cabal`. I'm building it with nix directly (described in the README) which makes the workaround very annoying.

**Comment by lrworth** [comment]
I guess it wasn't that hard to implement:

```
  ormolu = nixpkgs.haskell.packages."${ormoluCompiler}".ormolu.overrideAttrs (
    oldAttrs: rec {
      configureFlags = oldAttrs.configureFlags ++ [ "--ghc-option=-optP-Wno-nonportable-include-path" ];
    }
  );
```
but perhaps that ghc-option should be in the default.nix if it allows building on more OSes.

**Comment by mrkkrp** [comment]
@lrworth Do you want to open a PR?

**Comment by lrworth** [comment]
Absolutely I do.
