### ISSUE TITLE
Trailing spaces in multi-line comments.

### ISSUE THREAD

**Issue by fisx** [tweag/ormolu#603]
Another style feature request.

The attached file `Main.hs` should be idempotent, but it renders to `LayedOut.hs`, which has trailing whitespace in the empty lines in the comment.

[example.zip](https://github.com/tweag/ormolu/files/4722141/example.zip)

I don't like trailing whitespace because:

- break the rule that comments do not contain haskell syntax so you should be allowed to do whatever (could be i'm making this rule up just now, but still)
- it makes for noisier diffs and git inefficiencies
- breaks my emacs config where I remove trailing whitespace on save, *after* running ormolu (yes, this is easy to fix, but I think it's unnecessary)

I am interested in hearing whether you would consider accepting a PR for this (I'm not sure when I will have time, but me or somebody *might*).

**Comment by mrkkrp** [comment]
This looks like a bug to me.

**Comment by fisx** [comment]
> This looks like a bug to me.

thanks, i certainly won't argue with that.  :)
