### ISSUE TITLE
Enable all language extensions that don't steal identifiers

### ISSUE THREAD

**Issue by facundominguez** [tweag/ormolu#62]
This is an idea from @mboes.

If ormolu enables all extensions that don't steal syntax, it can then format a superset of Haskell.

It is then more debatable whether support for finding the `default-extensions` in cabal files (#56) is necessary. An extension that steals syntax is likely going to be activated per file, instead.

Are there any other factors we should consider when deciding which extensions to enable by default?

**Comment by mboes** [comment]
Mind, even those that steal syntax might well still format the same way. e.g. `-XStaticPointers` make `static` a keyword. But I don't see any reason to format that any differently than if that extension were not turned on. Ormolu doesn't care about the semantics - just the syntax.
