### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by lishine** [tweag/ormolu#625]
It is unclear, how to install ormolu using this
```
$ cat stack.yaml
resolver: lts-14.3
packages:
- '.'

$ stack build
```
I edited the stack.yaml:
- changed the resolver version
- changed - . into - '.'
- stack build

Ormolu still not installed

**Comment by mrkkrp** [comment]
`stack build` is for building, `stack install` is for installing. I'd recommend `lts-16.0`.

I believe `stack install` just copies the compiled binary to `~/.local.bin`, so make sure that path in on your `PATH`.

**Comment by lishine** [comment]
Great!
Indeed, all I needed to do is
stack install ormolu
It is for new project with 16+ resolver.
So the readme should be updated, that for stack only needed to do:
stack install ormolu

And the vscode extension works. Just select the ormolu formatter.

It formats great btw! Better than hie

**Comment by mrkkrp** [comment]
Good to hear! I mentioned `stack install` in the readme.

**Comment by lishine** [comment]
It should be
```stack install ormolu```
And the other stuff is not needed or at least confusing.
- If it works on latest - why mention 16.0? For example my version is 16.1
- What is - '.' (new project is created automatically and it is - . in stack.yaml (without '')
I say confusing because I am a beginner with Haskell and do exactly what is written.

**Comment by mrkkrp** [comment]
* I believe that `stack install ormolu` uses the version of the code from the Stackage snapshot, while we give instructions for building and installing the current version of code from the repo.
* `16.0` is for reproducibility. We know that it works with `16.0` so to ensure that your build will succeed. Sure, it also probably works `16.1` and others, but it does not matter.
* Re: confusing. Well, things that one has little experience with are generally confusing. It doesn't mean that they should be removed or avoided. You can read Stack's documentation to understand format of the `stack.yaml` file.
