### ISSUE TITLE
Formatting promoted constructor inside a promoted list

### ISSUE THREAD

**Issue by ilyakooo0** [tweag/ormolu#636]
**Describe the bug**
`ormolu` fails with when formatting promoted constructor inside a promoted list

**To Reproduce**

Try to format this file:

```haskell
module Fail where

type Foo = '[ 'TRegex "[A-Z]{3}" ]
```

**Expected behavior**
`ormolu` should format the code without errors

**Environment**
 - OS name + version:
macOS 10.15.5
 - Version of ormolu:
```
ormolu 0.1.2.0 UNKNOWN UNKNOWN
using ghc-lib-parser 8.10.1.20200523
```

**Comment by mrkkrp** [comment]
Indeed.
