### ISSUE TITLE
gfork high five

### ISSUE THREAD

**Issue by paolino** [tweag/ormolu#638]
Not an issue at all! 
I cannot find a better way to say *thank you* for the gfork branch,  which makes everything back as it was in my code base: lists, imports, tuples and SIGNATURES.
Please don't leave the fork behind, it's just as good as it can be and makes ormolu the best haskell formatter I ever used.

**Comment by jinwoo** [comment]
FYI. We created a forked repo of gfork at https://github.com/google/ormolu. Our intention is to keep that repo up to date with the new upstream changes.

**Comment by mrkkrp** [comment]
Glad you like it!
