### ISSUE TITLE
Support nested update syntax of record-dot-preprocessor 

### ISSUE THREAD

**Issue by pkapustin** [tweag/ormolu#659]
Currently, nested update syntax of record-dot-preprocessor is not supported.
So, something like this `company{owner.name = "John"}` results in a parse error.

I think it would be nice to support this as the nested update syntax is part of the record dot syntax proposal.
https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0282-record-dot-syntax.rst

**Comment by neongreen** [comment]
I suppose the GHC AST doesn't allow this, so it might be very tricky
