### ISSUE TITLE
Parse failure when mixing strictness annotation and Haddock comments on sum types

### ISSUE THREAD

**Issue by jkachmar** [tweag/ormolu#660]
**Describe the bug**
When `ormolu-0.1.3.0` is asked to format a region containing a sum type with strictness annotation and Haddock comments in a region that is technically valid Haskell (although it is a semantically invalid place to put a Haddock comment), it fails with the following error:
```
The GHC parser (in Haddock mode) failed:
  <stdin>:5:7
  parse error on input `!'
```

**To Reproduce**
Attempt to format a module with the following, Haskell code:
```haskell
data A
  = X
      !Int
      -- | Foo
      !Int
```
...observe that it fails with the error above.

**Expected behavior**
`ormolu-0.1.3.0` should format valid ADTs whose data constructors have strictness annotations and Haddock comments.

**Environment**
 - OS name + version: macOS 10.14.6 (Mojave)
 - Version of the code: 0.1.3.0

**Additional context**
After looking at this a bit more closely it seems that this error only crops up when placing the Haddocks in location that really doesn't make much sense (i.e. over the type associated with an unlabeled data constructor's parameters).

I can understand if this is an edge case that `ormolu` might not want or be able to support, so feel free to close this; it's not something I'm relying on or would want to contribute time to address.

**Comment by amesgen** [comment]
I don't think this is valid Haskell:
```
 Λ data A = !X | Y

<interactive>:1:10: error:
    Cannot parse data constructor in a data/newtype declaration:
      ! X
```

What would be the meaning of a strictness annotation on a 0-ary constructor anyway?

**Comment by jkachmar** [comment]
Whoops, my minimal reproduction wasn't actually that at all it was just invalid Haskell 😅 .

I've updated the comment with an _actual_ minimal reproduction of what I ran into.

**Comment by amesgen** [comment]
Ah, makes sense! Either way, this issue does not appear to be ormolu-specific, as the GHC parser just does not accept this code in haddock mode (I ran `cabal haddock` in a new `cabal init --lib` with your example added, and got the same error as above).

**Comment by mrkkrp** [comment]
If GHC parer fails, there is nothing we can do.

> Maybe one could think about introducing a flag to parse in non-haddock-mode for cases like this...

Switching between modes changes the ASTs quite a bit. Working with two modes is too much trouble, IMO.
