### ISSUE TITLE
DISABLED ormolu remove empty lines

### ISSUE THREAD

**Issue by ryukzak** [tweag/ormolu#673]
**Describe the bug**
I expect that ORMOLU_DISABLE can fully disable ormolu, but it continues removing empty lines.

**To Reproduce**
Input file:
```haskell
{- ORMOLU_DISABLE -}

module Foo (foo,bar) where



foo :: Int -> Int
foo = (+5)



bar :: Bool -> Bool
bar True  = True
bar False = True
```

Output file:
```haskell
{- ORMOLU_DISABLE -}

module Foo (foo,bar) where

foo :: Int -> Int
foo = (+5)

bar :: Bool -> Bool
bar True  = True
bar False = True
```

**Expected behavior**
Output source code should be identical to the input if I put `{- ORMOLU_DISABLE -}` at a file start.

```haskell
{- ORMOLU_DISABLE -}

module Foo (foo,bar) where



foo :: Int -> Int
foo = (+5)



bar :: Bool -> Bool
bar True  = True
bar False = True
```

**Environment**
 - OS name + version: MacOS X 11.0.1
 - Version of the code: ormolu 0.1.4.1

**Comment by brandon-leapyear** [comment]
Trailing spaces are also removed.

**Comment by kukimik** [comment]
> I expect that ORMOLU_DISABLE can fully disable ormolu, but it continues removing empty lines.

@ryukzak Note that there is an exception regarding the indentation level in the regions where formatting is disabled. See #601.
