### ISSUE TITLE
GADTs and haddock post-comments

### ISSUE THREAD

**Issue by ryukzak** [tweag/ormolu#677]
**Describe the bug**
A haddock post-comment works wrong with GADTs.

**To Reproduce**
Input:

```haskell
data Info a b where
    Cons1 :: a -> Info a b -- ^Cons 1 doc
    Cons2 :: a -> Info a b -- ^Cons 2 doc
```

Output:
```haskell
data Info a b where
  Cons1 ::
    a ->
    -- | Cons 1 doc
    Info a b
  Cons2 ::
    a ->
    -- | Cons 2 doc
    Info a b
```

**Expected behavior**
```haskell
data Info a b where
  -- | Cons 1 doc
  Cons1 :: a -> Info a b
  -- | Cons 2 doc
  Cons2 :: a -> Info a b
```

**Environment**
 - https://monadfix.com/ormolu/
 - Version of the code: ormolu commit a28f7b8, ormolu-live commit d8ae72e

**Comment by amesgen** [comment]
Maybe I am missing something, but I think that this is expected behavior. I created an example library exporting the input and the output, and the haddock in the input is indeed displayed at the return values, not at the constructors.

```
git clone --branch=gadt-haddock --single-branch https://github.com/amesgen/stuff
cd stuff
cabal haddock
# open the .html file displayed
```

**Comment by mrkkrp** [comment]
I think technically those comments are attached to the return type `Info a b`, not to the data constructors.
