### ISSUE TITLE
Extraneous newline in if-then-else

### ISSUE THREAD

**Issue by zuqq** [tweag/ormolu#678]
Formatting

```haskell
x =
  if undefined
    then ()
    -- comment
    else
      ()
```

with 4e01690e0586186735459b7b81eb0d5efbbbbdbe results in the following output:

```haskell
x =
  if undefined
    then ()
    else -- comment

      ()
```

with an extraneous newline after the `else` line.

This only happens with the comment on the line above and the body in hanging position:

```haskell
y =
  if undefined
    then ()
    else -- comment
      ()

z =
  if undefined
    then ()
    -- comment
    else ()
```

is correctly formatted as

```haskell
y =
  if undefined
    then ()
    else -- comment
      ()

z =
  if undefined
    then ()
    else -- comment
      ()
```

This behavior can also be observed in the example that was added by a5c4d6c439b01648cc44e307e0fe10e1a55c9bd5, but it is already present in earlier commits.

**Comment by mrkkrp** [comment]
As of version 0.7.6.0 this does not seem to happen anymore.
