### ISSUE TITLE
Not idempotent with comment in let-block

### ISSUE THREAD

**Issue by brandon-leapyear** [tweag/ormolu#687]
**Describe the bug**
The following source code will be reformatted twice:
```hs
foo :: IO ()
foo = let
  foo' = do
    putStrLn "hi"
  -- test
  in foo' >> putStrLn "bye"
```

**To Reproduce**
Run `ormolu` the first time gets
```diff
 foo :: IO ()
-foo =
-  let foo' = do
-       putStrLn "hi"
-       -- test
-  in foo' >> putStrLn "bye"
+foo = let
+  foo' = do
+    putStrLn "hi"
+  -- test
+  in foo' >> putStrLn "bye"
```
Run `ormolu` again rewrites it again to:
```diff
 foo :: IO ()
 foo =
   let foo' = do
         putStrLn "hi"
-  -- test
-  in foo' >> putStrLn "bye"
+  in -- test
+     foo' >> putStrLn "bye"
```
Any future runs of `ormolu` will not make any changes

**Expected behavior**
Should go from the original to the last change directly

**Environment**
 - OS name + version: Mac
 - Version of the code: `master` at `34bdf62`

**Additional context**

**Comment by mrkkrp** [comment]
As of 0.7.6.0 this example seems to be directly formatted in the latter version:

```haskell
foo :: IO ()
foo =
  let foo' = do
        putStrLn "hi"
   in -- test
      foo' >> putStrLn "bye"
```
