### ISSUE TITLE
Switch to ghc-lib-parser-9.0.1.xxx

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#688]
This should resolve some long-standing issues such as #474 and #480. Not sure how much work this is.

**Comment by brandonchinn178** [comment]
Would this be a switch (and thus dropping support for GHC < 8.8) or would this be expanding the bounds?

**Comment by mrkkrp** [comment]
Versions of `ghc-lib-parser` and GHC do not have to correspond. Thus, we will *switch* two `ghc-lib-paser-9.0.1.xxx` and *adjust* GHC bounds in order to support 3 latest versions of GHC, including 9.0.

**Comment by brandonchinn178** [comment]
Sure, so like I mentioned in my comment, this means dropping support for GHC < 8.8?

**Comment by mrkkrp** [comment]
Yes.
