### ISSUE TITLE
Make embeddable within other GHC API-based tools

### ISSUE THREAD

**Issue by chrisdone** [tweag/ormolu#69]
Given that parsing (and formatting) Haskell code tends to need information that is not lexically available, such as the fixity of operators imported from libraries or extensions enabled in cabal files or elsewhere, my natural inclination to have robust formatting would be to put it into `intero`, or `ghc-mod`, or `haskell-ide-engine` or whatever is the backend-du-jour.

Naturally, ormolu stands as a stand-alone tool like `hindent` and that's fine, but if it exposes a relatively simple Haskell API, then it can be imported by e.g. `intero`; Intero would parse the module itself using the proper flags and context, and it would pass the parsed AST over to `ormolu`.

Obviously, to be robust on "Real" code, you need to handle `CPP` to some degree like `hindent` tries to do. A user would want Ormolu to reformat with CPP taken into account, which is hard to do completely but doable in part. So that would be something to think about.

I've seen that the `ormolu` function already accepts a `Located (HsModule GhcPs)` via `parseModule'`, so it might just be a case of exposing the right fragment of the `ormolu` function.

If you're in agreement with this as a side-goal, I could pretty easily take a crack at importing ormolu from intero with a `:format` command (or so) and then open a PR here for scrutiny of what'd be necessary to expose in ormolu for an IDE backend to use it. You guys wouldn't necessarily have to do any work in the end.

One soft-requirement for intero is light dependency footprint (so that it's easy and fairly fast to install for users), and [ormolu's dependencies are quite light at the moment](https://github.com/tweag/ormolu/blob/master/ormolu.cabal#L38-L48), which is good. `yaml` does  bring a big footprint, but maybe that could be disabled with a flag. :thinking: Not sure. Technically people only need to install intero per GHC version nowadays, so it's less of a requirement. But I already regret adding the `network` dependency to intero, so... That's a delicate topic.

**Comment by facundominguez** [comment]
> Given that parsing (and formatting) Haskell code tends to need information that is not lexically available, such as the fixity of operators imported from libraries

This is an interesting point. Do you have any examples of code that should be formatted differently depending on the fixity?

> A user would want Ormolu to reformat with CPP taken into account, which is hard to do completely but doable in part. So that would be something to think about.

This is ruled out in the [design](https://github.com/tweag/ormolu/blob/master/DESIGN.md#cpp), but feel free to enter the discussion.

> Intero would parse the module itself using the proper flags and context, and it would pass the parsed AST over to ormolu

If https://github.com/tweag/ormolu/issues/62 works, it is not clear that we will need to discover much flags. I guess the motivation for integration then would be to:
1. Save parsing effort
2. Format fragments of a module rather than the whole thing

For the small price of exposing some internal functions, it could worth the trouble.

**Comment by chrisdone** [comment]
> This is an interesting point. Do you have any examples of code that should be formatted differently depending on the fixity?

With hindent people tend to want bespoke formatting for e.g. `<$>`, `<*>`, etc. and `$` specially handled, but a thing we wanted to do was automate that more based on fixity information. A simple example would be e.g.
```haskell
foo / bar * mu / foo / bar * mu  +
zot * pib / wib / zot * pib / wib
```
I don't know how ormolu currently decides where to put operators and line breaks, but the above is fairly reasonable that the `+` has lower precedence, therefore it makes sense to break there.

You could hard-code knowledge of Prelude operators, but handling it generally is cooler.

If Ormolu doesn't decide things like this, it might not make this issue as a whole worth it.

> This is ruled out in the design, but feel free to enter the discussion.

I'm all for that. Personally, I try to use cabal file flags for conditional compilation for stuff like that. :+1:

> For the small price of exposing some internal functions, it could worth the trouble.

Cool. FWIW, #62 is [basically what hindent does](https://github.com/chrisdone/hindent/blob/master/src/HIndent.hs#L231), and whose code was copied from hlint, which does the same thing. It _mostly_ works. I assume that GHC's parser takes the `{-# LANGUAGE ... #-}` extensions into account, right? In years of using hindent, the only two extensions I put in my config are
```lisp
(setq haskell-language-extensions '("-XMagicHash" "-XUnboxedTuples"))
```
so not much.

**Comment by mrkkrp** [comment]
It's OK with me. Whatever API you want to expose, go ahead and open a PR, I don't think there will be problems with that. I'm not super-happy about using `yaml` myself. As we discussed internally it would be best to somehow avoid need for any sort of configuration at all.

**Comment by mboes** [comment]
> yaml does bring a big footprint, but maybe that could be disabled with a flag. 

I think that dependency should be dropped. If we enable all language extensions, or require that all language extensions always be specified as pragmas in each source file, or a mix of both (see #62), then there should be no need for a configuration file anymore.

**Comment by mrkkrp** [comment]
The only actionable item from this issue seems to be dropping `yaml`. I'm going to close it once that's done.
