### ISSUE TITLE
Adding ORMOLU_DISABLE moves block

### ISSUE THREAD

**Issue by brandon-leapyear** [tweag/ormolu#693]
**Describe the bug**
Adding a `ORMOLU_DISABLE`/`ORMOLU_ENABLE` block before a `where` clause cause ormolu to move the block into the `where` clause

**To Reproduce**
```hs
asdf :: IO ()
asdf = do
  x <- foo
  {- ORMOLU_DISABLE -}
  return (x,x)
  {- ORMOLU_ENABLE -}
  where
    foo = pure 1
```

Running ormolu on this gives
```hs
asdf :: IO ()
asdf = do
  x <- foo
  where
    {- ORMOLU_DISABLE -}
    return (x,x)
    {- ORMOLU_ENABLE -}

    foo = pure 1
```
Same thing happens if the `ORMOLU` comments are not indented

**Expected behavior**
Code should stay the same

**Environment**
 - OS name + version: mac os
 - Version of the code: master

**Additional context**

**Comment by mrkkrp** [comment]
`ORMOLU_DISABLE` is only meant to be used around top-level forms, not selectively around expressions like this. I do not consider this a bug, a feature request perhaps.

**Comment by mrkkrp** [comment]
The readme says:

>  Because of that the magic comments cannot be placed arbitrarily, but rather must enclose independent top-level definitions.

**Comment by brandon-leapyear** [comment]
Interesting... I was able to work around this with
```hs
asdf :: IO ()
asdf = go
  where
    {- ORMOLU_DISABLE -}
    go = do
      x <- foo
      return (x,x)
    {- ORMOLU_ENABLE -}

    foo = pure 1
```
which works, so perhaps an undocumented feature? But yes, then this issue is a feature request

**Comment by mrkkrp** [comment]
The feature is a bit of a hack. Surely, it'll accidentally work is some cases, but this usage is not something we officially support.
