### ISSUE TITLE
Error on "-}" in regions with disabled formatting

### ISSUE THREAD

**Issue by kukimik** [tweag/ormolu#708]
**Describe the bug**
Parsing fails if the sequence of characters `-}` appears (in context other than a multiline comment) in a region where Ormolu is disabled using the magic comment.

**To Reproduce**
Run `ormolu` on the following input:

```
{- ORMOLU_DISABLE -}
a::String
a="-}"
```

This fails with:

```
<stdin>:3:7
  The GHC parser (in Haddock mode) failed:
  lexical error in string/character literal at character '\n'
```

**Expected behavior**
Unchanged data should be returned.

**Environment**
 - OS name + version: Linux 4.15.0-143-generic x86-64
 - Version of the code: 3adef733a99018c5e4437faaa0cc53b503c5d576 (ormolu 0.1.4.1 UNKNOWN UNKNOWN using ghc-lib-parser 8.10.2.20200916)

**Additional context**
My guess is that this follows from the way "disabled" regions are masked using a multi-line comment `{- ORMOLU_DISABLE_START ... ORMOLU_DISABLE_END -}` (see `Ormolu.Processing.Preprocess`).

If I am right, then it can perhaps be fixed by commenting out the "disabled" region by adding a prefix `-- ORMOLU_DISABLED` to each line in the region, instead of using the multiline comment. I think that with this approach #673 can also be easily fixed by modifying the following line to avoid removal of trailing spaces in "disabled" regions (and we'd avoid the removal of blank lines for free): https://github.com/tweag/ormolu/blob/3adef733a99018c5e4437faaa0cc53b503c5d576/src/Ormolu/Parser/CommentStream.hs#L107

**Comment by mrkkrp** [comment]
Your analysis is correct, however using line comments instead of mulitline comments will not solve it. We perform some normalization of all comments, which is why #673 happens. Proper fix required more profound changes.
