### ISSUE TITLE
Don't add a blank line between kind signatures and types

### ISSUE THREAD

**Issue by cdsmith** [tweag/ormolu#713]
Ormolu insists on adding a blank line between a kind signature and the corresponding type declaration.  This is inconsistent with functions, where it doesn't add a line after the type declaration.  I'd like it to omit that line for kind signatures, too.

**Comment by mrkkrp** [comment]
Fixed by #684 ?

**Comment by cdsmith** [comment]
Looks like it.  I guess I have an ormolu from before that patch.  Thanks!
