### ISSUE TITLE
Comment dropped after `-- $`

### ISSUE THREAD

**Issue by zliu41** [tweag/ormolu#721]
**Describe the bug**
When there's `-- $` in the comment, all comments afterwards are dropped.

**To Reproduce**
Input:

```haskell
lhs = rhs
  where
    -- Hello
    --
    -- $world
    --
    -- !
    rhs = rhs'
```

Output:

```haskell
lhs = rhs
  where
    -- Hello
    --
    rhs = rhs'
```

**Environment**
 - OS name + version: Ubuntu 21.04
 - Version of the code: 58108e0dcdb90b3e1bf82c7cce76024857145afd

**Comment by mrkkrp** [comment]
Probably the same as #474.

**Comment by aspiwack** [comment]
Indeed: `-- $` is reserved by Haddock for [named documentation chunks](https://haskell-haddock.readthedocs.io/en/latest/markup.html#named-chunks-of-documentation).

**Comment by mrkkrp** [comment]
Closing as a duplicate of #474.
