### ISSUE TITLE
case statement in do leads to parse error

### ISSUE THREAD

**Issue by ruhatch** [tweag/ormolu#73]
The input,
```haskell
module Main where

main :: IO ()
main = do
  case True of
    False -> pure ()
    True -> pure ()
  pure ()
```
, leads to the output,
```haskell
module Main where

main :: IO ()
main = do
  case True of
  False -> pure (())
  True -> pure (())
  pure (())
```
, which has two issues:

1) It doesn't parse, because the pattern matches have been lined up with `case`
2) It seems to have added extra `()` for some reason :man_shrugging:

**Comment by ruhatch** [comment]
This appears to be a problem with `case` when forced to be indented, as in this example:
```haskell
module Main where

main :: IO ()
main = -- comment
  case True of
    False -> pure ()
    True -> pure ()
```
leading to
```haskell
module Main where

main :: IO ()
main = -- comment
  case True of
  False -> pure (())
  True -> pure (())
```

**Comment by mrkkrp** [comment]
I noticed this last evening, and this is something I plan to fix this weekend.

**Comment by yumiova** [comment]
As for the problem with extra parentheses around unit:

I put about half an hour into researching the problem, and I figured I might as well mention the technical details if someone wants to fix it.

It seems to come from `p_rdrName`. Units are represented as `RdrName` with a case of `Exact`. When pretty printing the unit, it directly pretty prints `()`, as expected. However, `p_rdrName` queries the annotations of the `RdrName` in question, which obviously includes parentheses. Consequently, `parensWrapper` fires and adds another layer of parentheses on top, giving the characteristic extra layer of parentheses.

**Comment by mrkkrp** [comment]
Actually the bug with extra layout of parentheses is still there. I'll handle it next week.
