### ISSUE TITLE
Respect more newlines?

### ISSUE THREAD

**Issue by ruhatch** [tweag/ormolu#74]
This is really a question about how `ormolu` wants to treat newlines in general. I like to be liberal with whitespace to increase readability. For example I:

- Add newlines between groups of imports that I want to remain separate
- Add multiple newlines between sections within a single file
- Add newlines between expressions in a `do` block when each is a little complex
- Add newlines between bindings in a `where` block

It seems that `ormolu` will strip most of these out right now and I'm wondering how this should be treated in the future. One of the most interesting features of `ormolu`, for me at least, is the ability for the programmer to influence the output by, for example, adding line-breaks in type signatures. Newlines seem like another place where we can transfer some control to the programmer.

**Comment by mboes** [comment]
> Add newlines between groups of imports that I want to remain separate

We used to do this a lot on projects, but found it was counter productive. Managing the groups and moving them around meant bigger diffs and more cognitive overhead when adding imports (not to mention, harder for automatic tooling to add new ones at the right place) for little to no gain made this not worth it. So we have a monolithic set of imports that we sort alphabetically (like `haskell-mode` in Emacs does) and that's it.

> Add multiple newlines between sections within a single file

We normalize those, following long established precedent from Tibbe's style guide (also the basis of [Tweag's style guide](https://github.com/tweag/guides/blob/master/style/Haskell.md)). You can add comments in the middle if you really want more vertical space there.

> Add newlines between expressions in a do block when each is a little complex

Grouping statements sounds fair. Their order isn't arbitrary but dictated by the semantics you want.

> Add newlines between bindings in a where block

Also fair, but within a where block of bindings, they should either all have an intercalated newline or none of them.

**Comment by ruhatch** [comment]
> We used to do this a lot on projects, but found it was counter productive.

Fair enough, and I suppose one of the `ormolu` principles is to normalise that kind of stuff

> Also fair, but within a where block of bindings, they should either all have an intercalated newline or none of them.

Yeah, that seems reasonable to me. Maybe this can be similar to type signature, where any blank line between two definitions causes this intercalation behaviour?

A couple of other potential whitespace spots:
- Between language pragma list and module name (I find it quite unreadable having no space between those)?
- Between non-haddock comment and next top-level definition (it seems reasonable to close the gap between a `-- |` comment and a top-level def, but a `--` or `{- -}` block might not be related to that next def)?

**Comment by mboes** [comment]
> > within a where block of bindings, they should either all have an intercalated newline or none of them.
> 
> Yeah, that seems reasonable to me. Maybe this can be similar to type signature, where any blank line between two definitions causes this intercalation behaviour?

Yes. That makes total sense to me.

> Between language pragma list and module name (I find it quite unreadable having no space between those)?

Agreed.

> Between non-haddock comment and next top-level definition

Agreed. If there was no space line break initially, no need to add one. But if it was there, it's dangerous to remove that because as you say, the comment could be unrelated.

**Comment by mitchellwrosen** [comment]
+1 for _not_ re-styling

```haskell
do
  foo

  bar
  baz

  qux
  whomp
  wax
```

as

```haskell
do
  foo
  bar
  baz
  qux
  whomp
  wax
```

**Comment by pkamenarsky** [comment]
```

**Comment by pkamenarsky** [comment]
> Also fair, but within a where block of bindings, they should either all have an intercalated newline or none of them.

I'd argue that one might group let bindings by semantics as well. I.e:

```
something1 = ...

something 2 = ...

latitude = ...
longitude = ...
```

I find code much easier to read that way and putting newlines everywhere or nowhere might be too extreme?

**Comment by neongreen** [comment]
Another case: export lists. If I have Haddock headers in an export list, I put newlines between groups – and Ormolu eats them.

See for example http://hackage.haskell.org/package/pipes-4.3.11/docs/src/Pipes.Core.html: [before](https://gist.github.com/neongreen/66018eeaf0349031e4f6ae64635f3dd3), [after](https://gist.github.com/neongreen/1d51fa7c13c01d275e56f81e55dfe60d). Ormolu's variant is harder to navigate, especially when using navigation-by-paragraph (and I think it's harder to read as well, though of course one gets used to everything).

**Comment by neongreen** [comment]
And another case: separator comment blocks (e.g. in [Text.MMark.Parser](http://hackage.haskell.org/package/mmark-0.0.7.1/docs/src/Text.MMark.Parser.html)) get stuck to the next definition for no good reason. 

This is "after":

```haskell
----------------------------------------------------------------------------
-- Other helpers
slevel :: Pos -> Pos -> Pos
slevel a l = if l >= ilevel a then a else l

ilevel :: Pos -> Pos
ilevel = (<> mkPos 4)

isBlank :: Text -> Bool
isBlank = T.all isSpace
```

**Comment by alexpeits** [comment]
> We used to do this a lot on projects, but found it was counter productive.

I think it's worth preserving whitespace in imports. I agree it might be counter productive trying to sort imports from base and external packages (e.g. `Data.Text` is not in `base` but I always group it with `base` packages for some reason, and other people don't), but I'd argue it's very handy to have at least a group of the current package's imports and then all the others. Especially since (at least where I work) import lists tend to become pretty large.

**Comment by mrkkrp** [comment]
@alexpeits One solution is to make a custom prelude in that case. Single import section is what I think is the right thing. One of my clients first started by having several import sections but alas as the project progressed it became harder and harder to decide where a particular import should go. You really should not be wasting your time thinking about things like this. They merged all import sections in the end even before converting their code base to Ormolu.

**Comment by neongreen** [comment]
@cdsmith gives another example here: https://github.com/tweag/ormolu/issues/431.

**Comment by amesgen** [comment]
Another instance of respecting (missing) newlines:

```haskell
clientFunc1 :: SomeType1
clientFunc2 :: SomeType2
clientFunc3 :: SomeType3
clientFunc1 :<|> clientFunc2 :<|> clientFunc3 = hoistClient foo bar baz
```
is reformatted to
```haskell
clientFunc1 :: SomeType1

clientFunc2 :: SomeType2

clientFunc3 :: SomeType3
clientFunc1 :<|> clientFunc2 :<|> clientFunc3 = hoistClient foo bar baz

```
which is not perfect IMHO.

Should I create a seperate issue for this?

**Comment by mrkkrp** [comment]
Please do.

**Comment by cdsmith** [comment]
I just want to bump this.  This is, BY FAR, the number one thing keeping me from using Ormolu with my code.  It's not even close.  The worst of the worst here is what happens with `do` blocks (https://github.com/tweag/ormolu/issues/74#issuecomment-504614954), where ormolu is just plain turning thoughtfully written and well-formatted code into unreadable garbage.

It seems to me there are some very clear-cut lines around acceptable behavior here.

1. NEVER remove the last blank line between two segments of code.  Ever.  Period.  The programmer separated those segments for a reason, and a formatting tool should not remove the author's grouping.
2. Do not add blank lines between adjacent statements at the same level unless it's to add blank lines around a multi-line item with significant internal structure.
3. It's okay to remove duplicate blank lines, collapsing them into a single blank line.  If the author needs more separation, they can add a comment.
4. NEVER move statements around between different blocks separated by whitespace.  You are then changing the programmer's clearly stated decisions about grouping.

Currently, ormolu violates 1, 2, and 4.

**Comment by cdsmith** [comment]
@mrkkrp What's your gut reaction on this?  I'm willing to wait if ormolu is still getting around to fixing these things, but if there's fundamental disagreement on whether a formatter should change grouping in code, then I'd rather know that earlier rather than later.

**Comment by mboes** [comment]
1-4 sound reasonable to me.

**Comment by mrkkrp** [comment]
I’m all for respecting more newlines, but it’ll probably have to be implemented by someone else.

**Comment by michaelpj** [comment]
Just to echo that this is the main thing preventing me from using ormolu.

**Comment by ethercrow** [comment]
After using ormolu for several months this is my top 1 request, especially newlines within do-blocks.

**Comment by utdemir** [comment]
I also prefer preserving newlines in do-blocks, so I'll try to implement it these days. Probably I'll only focus on do-blocks, since we have well-defined newline logic on (most?) other constructs.

**Comment by mrkkrp** [comment]
This functionality is now part of Ormolu. I'm closing this issue because it's been a while and now we preserve newlines in a few places. If there are still special cases that we do not handle, please open new, more specific issues.

**Comment by ocharles** [comment]
Could we have documentation somewhere on exactly which are preserved?

**Comment by mrkkrp** [comment]
What’s the motivation for maintaining such a documentation (which is a nuisance as you can imagine)?

**Comment by ocharles** [comment]
To understand what Ormulu is and isn't capable of, in order to help evaluating the suitability of the tool
