### ISSUE TITLE
Breaks leading operator in arrow do block

### ISSUE THREAD

**Issue by robx** [tweag/ormolu#742]
**Describe the bug**

ormolu moves a leading operator in arrow do notation to the end of the previous line, breaking some code.

**To Reproduce**

```
$ cat test.hs
{-# LANGUAGE Arrows #-}

bar f = proc (a, b) ->
  do
    x <- f a -< b
    >-> (\y -> f b >- a)
$ ormolu test.hs
test.hs:6:5
  Parsing of formatted code failed:  parse error (possibly incorrect indentation or mismatched brackets)
$ ormolu --unsafe test.hs
{-# LANGUAGE Arrows #-}

bar f = proc (a, b) ->
  do
    x <- f a -< b >->
    (\y -> a -< f b)
```

**Expected behavior**

The code should be formatted to parseable code (with the same AST).

**Environment**

current master on macos

**Additional context**

- It seems like mirroring the code for monadic do notation a bit more closely. E.g., ormolu leaves the leading `+` as is in
```haskell
do
  return ()
  + 4
```
- The following change appears to fix the issue and doesn't break any code I can find, but I doubt it's correct as is:
```diff
--- a/src/Ormolu/Printer/Meat/Declaration/Value.hs
+++ b/src/Ormolu/Printer/Meat/Declaration/Value.hs
@@ -329,9 +329,10 @@ p_hsCmd' s = \case
       inci (sequence_ (intersperse breakpoint (located' p_hsCmdTop <$> cmds)))
   HsCmdArrForm NoExtField form Infix _ [left, right] -> do
     located left p_hsCmdTop
-    space
-    located form p_hsExpr
-    placeHanging (cmdTopPlacement (unLoc right)) $
+    breakpoint
+    inci $ do
+      located form p_hsExpr
+      space
       located right p_hsCmdTop
   HsCmdArrForm NoExtField _ Infix _ _ -> notImplemented "HsCmdArrForm"
   HsCmdApp NoExtField cmd expr -> do
```

**Comment by amesgen** [comment]
With #728 (but still with `--unsafe`), 

```haskell
{-# LANGUAGE Arrows #-}

bar f = proc (a, b) ->
  do
    x <- f a -< b
    >-> (\y -> f b >- a)
```

is formatted into

```haskell
{-# LANGUAGE Arrows #-}

bar f = proc (a, b) ->
  do
    x <- f a -< b
  >->
    (\y -> a -< f b)
```

which is better, but still not correct, as the first argument of `>->` in the original snippet is `proc (a, b) -> do x <- f a -< b` and not just `do x <- f a -< b` (which it is in the second snippet), so the AST differs.

I will look into this.

**Comment by amesgen** [comment]
With #728 (but still with `--unsafe`), 

```haskell
{-# LANGUAGE Arrows #-}

bar f = proc (a, b) ->
  do
    x <- f a -< b
    >-> (\y -> f b >- a)
```

is formatted into

```haskell
{-# LANGUAGE Arrows #-}

bar f = proc (a, b) ->
  do
    x <- f a -< b
  >->
    (\y -> a -< f b)
```

which is differing AST, but only due to `f b >- a` vs. `a -< f b`. So this is another instance of #737, closing as a duplicate.
