### ISSUE TITLE
Arrow operator misformatting (another case)

### ISSUE THREAD

**Issue by robx** [tweag/ormolu#748]
**Describe the bug**
Another one, similar to #742. Again, operators in arrow syntax are involved, and it appears to need at least two instances to fail.

I'm finding these issues from running ormolu against https://github.com/hasura/graphql-engine by the way, in case that helps verify solutions.

**To Reproduce**

```
$ cat test.hs
{-# LANGUAGE Arrows #-}

bar f = proc (a, b) -> do
    (f a -< b)
      >-> (\y -> f b >- a)
      >-> (\y -> f b >- a)
$ ormolu test.hs
test.hs
  AST of input and AST of formatted code differ.
    at test.hs:(3,24)-(6,26)
  Please, consider reporting the bug.
$ ormolu -u test.hs
{-# LANGUAGE Arrows #-}

bar f = proc (a, b) -> do
  (f a -< b) >->
    (\y -> f b >- a)
  >->
    (\y -> f b >- a)
```

**Expected behavior**
The code should be formatted to parseable code (with the same AST).

**Environment**
current master (post-0.2) on macos

**Comment by amesgen** [comment]
> I'm finding these issues from running ormolu against https://github.com/hasura/graphql-engine by the way, in case that helps verify solutions.

Thanks! I opened #752 and #753 by trying to format graphql-engine.
