### ISSUE TITLE
AST differs on Haddock comment on infix constructor

### ISSUE THREAD

**Issue by amesgen** [tweag/ormolu#758]
**Describe the bug**
This snippet can't be formatted without `--unsafe` (minimized from [Agda](https://github.com/agda/agda/blob/3376fcd27edebfa90a3267cb26187f4bc6318c96/src/full/Agda/Syntax/Internal.hs#L641-L647)):

```haskell
data A = A :# A -- ^ foo
```

With `--unsafe`, it is formatted to
```haskell
data A
  = -- | foo
    A :# A
```

In the first case, the Haddock comment is attached to the constructor `:#`, but in the second case, it is attached to the first argument of `:#`.

**Expected behavior**
It could be formatted like this to preserve the AST:

```haskell
data A
  = A
      -- | foo
      :# A
```
But this is not really nice from a sylistic perspective (we should not have to break apart an existing single line constructor variant).

**Environment**
Ormolu 0.2.0.0

**Additional context**
This changed in GHC 9.0; previously, both snippets had the same AST.

**Comment by brandonchinn178** [comment]
I opened a GHC ticket for this: https://gitlab.haskell.org/ghc/ghc/-/issues/24221

But aside from that issue, it seems like Ormolu doesn't format a fully documented infix constructor correctly anyway. Here's an example:

```hs
data Foo
  = Int -- ^ Docs for left arg
    :*: -- ^ Docs for constructor
    Int -- ^ Docs for right arg
```

This fails to output valid Haskell:
```hs
<input>
@@ -1,4 +1,8 @@
  data Foo
-   = Int -- ^ Docs for left arg
-     :*: -- ^ Docs for constructor
-     Int -- ^ Docs for right arg
+   = -- | Docs for constructor
+
+     -- | Docs for left arg
+     Int
+       :*: -- | Docs for right arg
+       Int
+

  AST of input and AST of formatted code differ.
    at <input>:2:5-7
    at <input>:2:9-30
  Please, consider reporting the bug.
  To format anyway, use --unsafe.
```

**Comment by brandonchinn178** [comment]
FYI GHC 9.10 fixed the issue originally documented. But I'll fix the issue I brought up in the thread
