### ISSUE TITLE
EmptyCase brackets disappear

### ISSUE THREAD

**Issue by noughtmare** [tweag/ormolu#765]
**Describe the bug**

When writing an empty case expression I'm used to writing the layout brackets `{}` explicitly to avoid confusion, but ormolu removes them.

**To Reproduce**

```
$ echo "case () of {}" | ormolu
case () of
```

**Expected behavior**

```
$ echo "case () of {}" | ormolu
case () of {}
```

**Environment**
 - OS name + version: NixOS 21.05
 - Version of the code: 
      ormolu 0.1.4.1 UNKNOWN UNKNOWN
      using ghc-lib-parser 8.10.4.20210206
      (from nixpkgs)

**Comment by amesgen** [comment]
Here is a case where we *have* to insert braces:

```haskell
foo x =
  case x of {}
    1
```
is formatted (with `--unsafe`) into
```haskell
foo x =
  case x of
    1
```
which can not be parsed.
