### ISSUE TITLE
Extract stack.yaml from README.md

### ISSUE THREAD

**Issue by hseg** [tweag/ormolu#776]
Having it included inline means packagers need to pay attention to another source of truth.
eg the AUR package linked still is using `lts-15.11` because the packager forgot to pay attention.

**Comment by amesgen** [comment]
Good idea, I created #777 for this. Additionally, I published [ormolu-bin](https://aur.archlinux.org/packages/ormolu-bin/) to the AUR which uses the official [release binaries](https://github.com/tweag/ormolu/releases) instead of building ormolu from scratch.
