### ISSUE TITLE
Typo "screw" in DESIGN.md?

### ISSUE THREAD

**Issue by glebec** [tweag/ormolu#795]
**Describe the bug**
[DESIGN.md#L115-116](https://github.com/tweag/ormolu/blob/dfcbf90b2b0f7673645b2f19790697b1f32628d2/DESIGN.md?plain=1#L115-L116) states:

> As I understand it, people mostly use it to screw their import lists.

I assume this was meant to say "sort," not "screw," unless "screw" is some import terminology I'm unfamiliar with.

**Comment by mrkkrp** [comment]
Thanks for catching up this unfortunate misspelling! Fixed in c7ede90.
