### ISSUE TITLE
Leading space added when a multiline invalid haddock comment is located at top-level

### ISSUE THREAD

**Issue by tbagrel1** [tweag/ormolu#816]
When a haddock comment is:

- located at top level AND
- invalid in this context AND
- multiline

Then the  `mkComment` function (in `CommentStream.hs`) get the wrong `n = minimum (startIndent : fmap getIndent xs)` number of leading spaces to drop in front of subsequent comment lines (it always results in `n == 0` because `startIndent == 0` in this case).

As a result, the space following `--` in `-- this is the second line of my comment` gets included in the actual comment string, to which `commentPrefix == "-- "` is then prepended. Thus, we get `--  this is the second line of my comment`.

This can't be reproduced in regular modules (only in signature files), because in regular modules, a top-level haddock comment can't be invalid AFAIK. We also can't reproduce it with non top-level comments, because in that case `startIndent > 0` so `n` gets the correct value.

Example:

```haskell
signature Implementation ( Prim
                         , name
                         , primName
                         , randomBlocks
                         ) where

import Raaz.Www
import Raaz.Core

data Prim
instance Primitive Prim

name :: String
-- | The name of the primitive used as the seed stretcher
-- second line of comment
primName :: String
randomBlocks :: AlignedBlockPtr BufferAlignment Prim
             -> BlockCount Prim
             -> Internals
             -> IO ()
```

**Comment by tbagrel1** [comment]
@mrkkrp, IIRC, you said that we needed to drop "hackage triggers" on lines 2+ if the whole haddock comment is invalid (instead of prepending a space before the trigger to deactive it)

But if we do what you suggested, then it become harder for things like this
```haskell
f =
  -- | Invalid
  -- || haddock comment
  2
```
to be formatted properly, because we would need to drop chars from the comment string while the first char is a haddock trigger.
But then, we would need a special case so that
```haskell
  -- | Invalid
  -- | comment
```
is formatted like that
```haskell
  -- Invalid
  -- comment
```
(notice the dropped space)

But that
```haskell
  -- | Invalid
  -- | | haddock
```
is formatted like that
```haskell
  -- Invalid
  --  | haddock
```
(if we drop the space in the last case, then we create an invalid haddock comment again)

So, should we stay on this idea, or just add a space to deactivate the haddock trigger (like before) in that context?

**Comment by mrkkrp** [comment]
Let's try to use escaping to solve this. Instead of dropping pipes and other such characters on the second line and later, insert a backslash thus escaping the problematic character:

```haskell
foo x = x
-- | abc
-- | def
foo x = x
```

should then turn into:

```haskell
foo x = x
-- abc
-- \| def
foo x = x
```

**Comment by tbagrel1** [comment]
I implemented a fix for this issue, using backslash escaping, but I found a case where ormolu still fails:
```haskell
foo =
  -- || b
  -- c
  b
```
i.e, when an invalid haddock comment starts with two haddock triggers.
The first one get removed automatically (because the haddock comment is invalid), but then the second one creates a new invalid haddock comment.

I can't use the backslash escaping trick here, because the first haddock trigger seems definitively lost (I don't know whether GHC-lib-parser or ormolu is responsible for this removal), so we wouldn't get a consistent behaviour with subsequent lines:
```haskell
foo =
  -- || b
  -- || c
  b
```
would become
```haskell
foo =
  -- \| b
  -- \|| c
```
which is rather unsatisfying
