### ISSUE TITLE
Unparseable output on comment after type synonym (but before the `=`)

### ISSUE THREAD

**Issue by amesgen** [tweag/ormolu#829]
**Describe the bug**
The snippet
```haskell
type A -- foo
  = B
```
is formatted into
```haskell
type A -- foo
=
  B
```
which can not be parsed.

**Environment**
0.3.1.0 and e003e11a569f9801b2a3f0cc01a66c883d597a3d

**Additional context**
Found via #821

Can also be triggered via type families.
```haskell
type family A a where
  A Int -- foo
    = Int
```

**Comment by amesgen** [comment]
I pushed an easy fix to [`amesgen/issue-829`](https://github.com/tweag/ormolu/tree/amesgen/issue-829) which fixes the bug, but the output is not particularly beautiful:
```haskell
type A -- foo
  = B
```
to
```haskell
type A -- foo
  =
  B
```
(it would be "nicer" if the `B` would be on the same line as the `=`)

But to my surprise, this is consistent with its value-level equivalent:
```haskell
a -- foo
  = b
```
to
```haskell
a -- foo
  =
  b
```

Do we want to fix both or leave them as is?

**Comment by mrkkrp** [comment]
Ideally we would like to keep both `B` and `b` on the same line as `=`, but I do not know what hard that would be.

**Comment by amesgen** [comment]
I agree. What about merging the small fix above and then opening a style issue for formatting this idiom more beautifully (not only for type synonyms, but also for values/functions/type families/pattern synonyms, as they all have the same style issue)?
