### ISSUE TITLE
Parse error for inline block comment with leading *

### ISSUE THREAD

**Issue by Gabriel439** [tweag/ormolu#833]
**Describe the bug**

`ormolu` fails on inline block comment with leading `*`

**To Reproduce**

The following code triggers the problem:

```haskell
example = 1 {- * 2 -} * 3
```

I'm actually using `fourmolu`, but I assume this issue originates in the upstream `ormolu`:

```ShellSession
$ fourmolu test.hs
…
The GHC parser (in Haddock mode) failed:
  test.hs:1:13-19
  parse error on input `{- * -}'
```

**Expected behavior**

There shouldn't have been a parse error since the code is accepted by `ghc` without error.

**Environment**

 - OS name + version: macOS Monterey 12.0.1
 - Version of the code:

  ```ShellSession
  $ fourmolu --version
  fourmolu 0.3.0.0 UNKNOWN UNKNOWN
  using ghc-lib-parser 8.10.1.20200412
  ```

**Comment by amesgen** [comment]
This seems to be fourmolu-specific, with Ormolu 0.3.1.0 your snippet is formatted without error to
```haskell
example = 1 {- * 2 -} * 3
```

**Comment by amesgen** [comment]
Also, you seem to be using an old fourmolu version, latest version is 0.4.0.0 which uses ghc-lib-parser-9.0 which has changes regarding Haddock comments (I think the issue here is/was that {O,Fou}rmolu run in Haddock mode and your comment is regarded as an invalid Haddock comment).

**Comment by Gabriel439** [comment]
Ah, it looks like I just need to upgrade, then.  Thanks for debugging this!
