### ISSUE TITLE
Ormolu uses -- ^ style to annotate arguments of a data constructor

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#844]
Ormolu currently transforms this snippet

```haskell
-- | Foo.
data Foo
  = Foo
      -- | Bar
      Char
      -- | Baz
      Int
```

into

```haskell
-- | Foo.
data Foo
  = Foo
      Char
      -- ^ Bar
      Int
      -- ^ Baz
```

which seems to be at odds with how we format Haddocks in other contexts. The version with pipes (`-- |`) is accepted by the latest `ghc-lib-parser` and so it makes sense to migrate to that style someday.

**Comment by amesgen** [comment]
Just for the record:

```haskell
-- | Foo.
data Foo
  = Foo
      -- | Bar
      Char
      -- | Baz
      Int
```
started to parse (in Haddock mode) with GHC 9.0.1. Hence, we probably only should change the style here when GHC <9.0 is not used that much, as making Haddock suddenly fail is probably a bad experience.

**Comment by mrkkrp** [comment]
Yeah, I think we should wait a little bit and change when 9.4 is out.
