### ISSUE TITLE
Investigate Ormolu Live page load failures

### ISSUE THREAD

**Issue by amesgen** [tweag/ormolu#862]
Several people (e.g. in https://github.com/tweag/ormolu/issues/861) independently reported that they can't load https://ormolu-live.tweag.io for some reason. I can't reproduce this in the latest Firefox (desktop & mobile), Chromium and Chrome. 

It would be interesting to find out why this happens and resolve this issue.

**Comment by andreasabel** [comment]
I am seeing in the Chrome JavaScript console:
```
JavaScript exception: TypeError: Cannot read properties of null (reading 'appendChild')
```

**Comment by andreasabel** [comment]
Works for me now: 
> Version 0.4.0.0, commit [8fa481d](https://github.com/tweag/ormolu/commit/8fa481d42a982d1637111916fb5703d26e2677d3), using ghc-lib-parser 9.2.1.20220109
