### ISSUE TITLE
Remove identation in ORMOLU_DISABLE section 

### ISSUE THREAD

**Issue by ryukzak** [tweag/ormolu#865]
**Describe the bug**

Usecase: some times we have regular boilerplate code which will be better to format manually. E.g.

Input:
```haskell
data A = A {a :: (), bbbbbbbbbbbb :: (), cccccc :: ()}

foo
  ( A
      a
      bbbbbbbbbbbb
      cccccc
    ) =
    concat
{- ORMOLU_DISABLE -}    
      [ "a"            <> show a
      , "bbbbbbbbbbbb" <> show bbbbbbbbbbbb
      , "cccccc"       <> show cccccc
      ]
{- ORMOLU_ENABLE -}
```

**To Reproduce**
Execute ormolu (from here: https://monadfix.com/ormolu) and receive the following:

```haskell
data A = A {a :: (), bbbbbbbbbbbb :: (), cccccc :: ()}

foo
  ( A
      a
      bbbbbbbbbbbb
      cccccc
    ) =
    concat

{- ORMOLU_DISABLE -}
[ "a"            <> show a
, "bbbbbbbbbbbb" <> show bbbbbbbbbbbb
, "cccccc"       <> show cccccc
]
{- ORMOLU_ENABLE -}
```

**Expected behavior**

Source code should not be changed.

**Environment**
 - https://monadfix.com/ormolu
 - Actual I work with fourmolu.

**Comment by amesgen** [comment]
This is already the case in recent versions (since 0.3.0.0, where the handling of disabled regions was changed).

Also: https://monadfix.com/ormolu is outdated, but you can use https://ormolu-live.tweag.io instead, see https://github.com/tweag/ormolu#ormolu-live.
