### ISSUE TITLE
Life demo does not demonstrate line breaks sensibly?

### ISSUE THREAD

**Issue by andreasabel** [tweag/ormolu#871]
At https://ormolu-live.tweag.io/ I entered:
```haskell
import Fooslkfgjdlkfjgldkfjgldkfjglkdjfglkdjflgkdjflgkdjfg.Baseflksd.HUrzu.Fan (x,y,z,a,s,q,w,e,r,t,u,i,o,p,g,h,j,k,l,m)
```
It is not demonstrated how this is broken into several lines (is it)?  I tried several variants but could not get it to line-break.

Anyway, the screenshot does not look inspiring:
<img width="997" alt="Screenshot 2022-04-09 at 22 53 27" src="https://user-images.githubusercontent.com/1155218/162591325-a86b02a6-00db-45e3-8390-c86a84c10d12.png">

**Comment by mrkkrp** [comment]
Ormolu does not break lines for you. It is explained at the top of the readme:

> Let some whitespace be programmable. The layout of the input influences the layout choices in the output. This means that the choices between single-line/multi-line layouts in certain situations are made by the user, not by an algorithm. This makes the implementation simpler and leaves some control to the user while still guaranteeing that the formatted code is stylistically consistent.

**Comment by andreasabel** [comment]
Ok, I was somehow expecting differently after some VSCode sessions (which I thought used `ormolu`, but I might be mistaken).
Thanks for the explanation!

**Comment by mrkkrp** [comment]
If there is a line break in a construction it will be reformatted the multilne way, e.g.:

```haskell
foo :: Int
  -> Int -> Int -> Int
```

becomes

```haskell
foo ::
  Int ->
  Int ->
  Int ->
  Int
```

in this case some newlines are introduced.

However a single-line construction will always stay single-line (as is the case with the import).
