### ISSUE TITLE
Awkward formatting of single-constructor record with a Haddock

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#881]
See https://github.com/tweag/ormolu/issues/583#issuecomment-1120317998

Ormolu outputs data definitions such as this one

```haskell
data FutureSumType = -- | This is what the documentation for this type looks like.
  -- It is pretty awkward that the @--@s aren't aligned.
  SingleConstructor
  { someRecordField :: Bool,
    someOtherRecordField :: Int
  }
```

which is not nice. We want to insert a newline in front of `-- |` in these cases.

**Comment by lehmacdj** [comment]
Thanks for fixing this!
