### ISSUE TITLE
Diff displays hunks incorrectly in some cases

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#886]
When diffing these two inputs:

```haskell
testPermParser :: Permutation Parser String
testPermParser =
  f <$> toPermutationWithDefault 'x' (char 'a')
    <*> toPermutationWithDefault 'y' (char 'b')
    <*> toPermutationWithDefault 'z' (char 'c')
  where
    f a b c = [a, b, c]
```

and

```haskell
testPermParser :: Permutation Parser String
testPermParser =
  f
    <$> toPermutationWithDefault 'x' (char 'a')
    <*> toPermutationWithDefault 'y' (char 'b')
    <*> toPermutationWithDefault 'z' (char 'c')
  where
    f a b c = [a, b, c]
```

The result is

```diff
@@ -148,5 +148,6 @@
  testPermParser :: Permutation Parser String
  testPermParser =
-   f <$> toPermutationWithDefault 'x' (char 'a')
+   f
+     <$> toPermutationWithDefault 'x' (char 'a')
    where
      f a b c = [a, b, c]
```

which is not correct. Instead of the line with `where` it is the line with `<*> toPermutationWithDefault 'y' (char 'b')` that should follow. Proper diff reports:

```diff
@@ -147,7 +147,8 @@ prsp' p = prs' (runPermutation p)

 testPermParser :: Permutation Parser String
 testPermParser =
-  f <$> toPermutationWithDefault 'x' (char 'a')
+  f
+    <$> toPermutationWithDefault 'x' (char 'a')
     <*> toPermutationWithDefault 'y' (char 'b')
     <*> toPermutationWithDefault 'z' (char 'c')
   where
```

We should match that.

This seems to have been broken ever since I introduced the functionality for nice displaying of diffs.

**Comment by mrkkrp** [comment]
I'm surprised that this did not come up earlier and I did not notice it before...

**Comment by amesgen** [comment]
> I'm surprised that this did not come up earlier and I did not notice it before...

Personally, I think I never looked at the diffs produced by Ormolu more than in a binary "oh, it is not yet formatted" fashion, but rather used the diffing of the git project I was formatting afterwards for inspection. One possibility would be to just shell out to `git diff` if available, and don't display diffs otherwise, but the diff printing code in Ormolu is not *that* large/complex that this seems like a priority.

**Comment by mrkkrp** [comment]
`git diff` approach is what was used before. I think there is a problem with it though, git diffing and Ormolu diffing are not always the same, in particular, they are not the same in the presence of intermediate editing. Actually IIRC that was the reason for adding built-in diffing in Ormolu: if I wanted to check on CI with Ormolu I had to use `git diff`, but my script also did some other editing and it interfered with the results.

**Comment by amesgen** [comment]
One could use `git diff --no-index` to just use the diffing part and ignoring any changes
