### ISSUE TITLE
ormolu breaks top-level module description/comment

### ISSUE THREAD

**Issue by blackheaven** [tweag/ormolu#890]
**Describe the bug**
Whenever I try to make top-level comment for hackage, ormolu breaks them.

**To Reproduce**
Try these headers:

```
-------------------------------------------------------------------------------
-- |
-- Module : ...
-- Copyright : ...
-- License : ...
-- Maintainer : ...
-- Stability : provisional
-- Portability : GHC
--
-- ...
-------------------------------------------------------------------------------
```

From `0.1` to `0.4`, you'll get:

```

-------------------------------------------------------------------------------

-------------------------------------------------------------------------------

-- |
-- Module : ...
-- Copyright : ...
-- License : ...
-- Maintainer : ...
-- Stability : provisional
-- Portability : GHC
--
-- ...
```

You'll get that in `0.5.0.0`:

```

-------------------------------------------------------------------------------

-- |
-- Module : ...
-- Copyright : ...
-- License : ...
-- Maintainer : ...
-- Stability : provisional
-- Portability : GHC
--
-- ...

-------------------------------------------------------------------------------
```

**Expected behavior**
I expect the input to stay unchanged.

**Environment**
 - OS name + version: NixOS unstable
 - Version of the code: `0.1` to `0.5`

**Additional context**
.

**Comment by mrkkrp** [comment]
Technically, the Haddock starts with `-- |`, not with `---`. So what Ormolu does makes sense to me.

Why do you need those lines of dashes?

**Comment by blackheaven** [comment]
I'm not sure, all the examples I encountered have them, I've never tried without, maybe it worth a test on my side.

**Comment by blackheaven** [comment]
It works without, thanks, sorry for the bug report.
