### ISSUE TITLE
Performance regression in `ormolu` HEAD

### ISSUE THREAD

**Issue by parsonsmatt** [tweag/ormolu#897]
**Describe the bug**

We were running `fourmolu-0.3.0.0` to format all of our code at work, and it would take about a minute for 3,000+ source files and 250kloc. I upgraded to `fourmolu-0.7.0.0` which is based on `ormolu-0.5.0.0` and this resulted in a massive slowdown: the same task now takes 20-30 minutes to run. I've tested `ormolu-0.5.0.0` (installed from Hackage, as well as HEAD on `master` here) and the performance problem remains.

As described in #896 , you can get nice multithreading which ameliorates the problem using `fd` (thanks @amesgen!). On my machine, this decreased the time to about 5 minutes. This is acceptable, but not ideal.

I got `HEAD` building with this diff to `stack.yaml`:

```patch
diff --git a/stack.yaml b/stack.yaml
index cf17657..64026cf 100644
--- a/stack.yaml
+++ b/stack.yaml
@@ -1,4 +1,4 @@
-resolver: lts-19.2
+resolver: lts-19.11
 
 packages:
 - '.'
@@ -7,7 +7,7 @@ packages:
 
 extra-deps:
 - Cabal-3.6.2.0
-- ghc-lib-parser-9.2.1.20211101
+  # - ghc-lib-parser-9.2.1.20211101
 
 nix:
   packages:
```

Building with this command:

```
stack install . --executable-profiling --resolver nightly --library-profiling --profile
```

And finally running on three large test files (about 9kloc between them):

```
ormolu --mode check src/Client/Apex/Types/Atlas.hs test/Gen.hs src/Client/Bank/Primitive.hs +RTS -p -RTS
```

The top few lines of the profile give `everywhere` and `thenP` as our pproblems, taking up 38% of runtime.

```
	Tue Jun 14 10:15 2022 Time and Allocation Profiling Report  (Final)

	   ormolu +RTS -p -RTS --mode check src/Client/Apex/Types/Atlas.hs test/Gen.hs src/Client/Bank/Primitive.hs

	total time  =        8.49 secs   (8487 ticks @ 1000 us, 1 processor)
	total alloc = 5,711,086,104 bytes  (excludes profiling overheads)

COST CENTRE                                 MODULE                              SRC                                                                   %time %alloc

everything.go                               Data.Generics.Schemes               src/Data/Generics/Schemes.hs:122:5-37                                  22.1    4.1
thenP.\                                     GHC.Parser.Lexer                    compiler/GHC/Parser/Lexer.x:(2396,9)-(2398,40)                         16.4    1.8
==                                          Distribution.Utils.ShortText        src/Distribution/Utils/ShortText.hs:96:29-30                            4.2    0.0
matchIgnoringSrcSpans.genericQuery          Ormolu.Diff.ParseResult             src/Ormolu/Diff/ParseResult.hs:(77,5)-(104,32)                          3.9    0.0
<>.combineNub                               Distribution.Types.BuildInfo        src/Distribution/Types/BuildInfo.hs:215:7-44                            3.7    0.1
getExtensionAndDepsMap.buildMap             Ormolu.Utils.Cabal                  src/Ormolu/Utils/Cabal.hs:(164,5)-(167,40)                              2.1    0.4
ext1                                        Data.Generics.Aliases               src/Data/Generics/Aliases.hs:326:1-43                                   1.5    1.4
linesInRegion                               Ormolu.Processing.Common            src/Ormolu/Processing/Common.hs:(38,1)-(41,67)                          1.3    4.6
gfoldlAccum                                 Data.Generics.Twins                 src/Data/Generics/Twins.hs:(91,1)-(94,26)                               1.2    0.1
```

I've generated a flamegraph from this profile:

![02-head](https://user-images.githubusercontent.com/7310112/173626601-79bbbebc-1a0c-4beb-ac62-47bce7416b79.svg)

This points to a potential regression in the `Data.Generics.Schemes` code. I'm curious if we have a regression that is related to Simplified Subsumption, since that module makes heavy use of the `GenericQ` type alias, which is `type GenericQ r = forall a. Data a => a -> r`. 

[`everything` is defined here](https://www.stackage.org/haddock/nightly-2022-06-14/syb-0.7.2.1/src/Data.Generics.Schemes.html#everything), and it is used in `ormolu` through the `listify` function.

**Comment by mrkkrp** [comment]
@parsonsmatt Have you had a chance to try out @amesgen's suggestion?

**Comment by avieth** [comment]
> @parsonsmatt Have you had a chance to try out @amesgen's suggestion?

I applied the patch to fourmolu 0.7.0.1 (ormolu 0.5.0.0) and noticed a small reduction in total allocation (about 10MB) and no noticeable improvement in run time.

fourmolu 0.5.0.1 (based off of ormolu 0.4.0.0) on the same input set was noticeably faster with less than half the total allocation.

**Comment by amesgen** [comment]
Any chance you have a file/set of files which demonstrate the huge performance regression you could share? I would love to investigate further, but it is a bit difficult without sth concrete.

**Comment by avieth** [comment]
> Any chance you have a file/set of files which demonstrate the huge performance regression you could share? I would love to investigate further, but it is a bit difficult without sth concrete.

Not able to share the file I was running it on due to licensing. However I was toying around some more trying to get an example I _can_ share, and found that the slowness and high allocations actually depends upon _where_ the file is. So naturally I tried `--no-cabal`, manually passing the extension I need, and that gives a huge performance boost (allocations down by half).

**Comment by 9999years** [comment]
It looks like ormolu is parsing the `.cabal` file for _every_ source file it processes. With 3000 modules and a 9000-line `.cabal` file, that gets expensive quickly.

@parsonsmatt also noted that "it's doing a recursive filesystem search on every file, too, so for a super deeply nested module, it's going to explode in the amount of work done."

Hopefully it's relatively easy to memoize these functions.

https://github.com/tweag/ormolu/blob/84a3f0eabadb72773e6057f74b1e82c50b9cf5b1/src/Ormolu/Utils/Cabal.hs#L70-L75

**Comment by amesgen** [comment]
@9999years That seems reasonable (in fact, we discussed whether it is worth it to reuse the parsed `.cabal` file, but it didn't make much difference in a few test projects, but certainly not as extreme as that example).

In the [profiling report above](https://user-images.githubusercontent.com/7310112/173626601-79bbbebc-1a0c-4beb-ac62-47bce7416b79.svg), `.cabal` source file parsing doesn't seem to account for a lot of time (at least, not enough to explain the huge regression from 1min to >20min). Maybe in the actual codebase, there are lots of small modules, for each of which the huge `.cabal` file has to be parsed? That could indeed be the culprit.

Memoizing/caching this function should be easy (we already do so in several other places), I will take a look :+1:

**Comment by parsonsmatt** [comment]
My first impression is "Just find the `.cabal` file and parse it once before doing any other work," but that's fragile if there are multiple cabal files and you're formatting a big project.

My *next* impression is to have a `Trie Directory GenericPackageDescription` where the most specific `.cabal` file is selected for a specific directory prefix, and we stuff that in an `MVar` which can be shared among threads.

> Maybe in the actual codebase, there are lots of small modules, for each of which the huge .cabal file has to be parsed? That could indeed be the culprit.

We have 3,301 modules between `src` and `test`. Parsing the cabal file appears to take 5% of the time taken for that profile, or `8.49 * 0.05 = 0.42s * 3301 = 1386s / 60 = 23.1 minutes`. Which accounts for *most* of the slowdown we're experiencing, though not all.

**Comment by amesgen** [comment]
I implemented quick&dirty caching of `.cabal` files here: https://github.com/tweag/ormolu/tree/amesgen/issue-897-cache-cabal-parsing

I just ran it on purescript-0.14.5 (`fd -e hs -X ormolu -m check`), which has a 500 line `.cabal` file and 174 modules, and runtime decreased from ~9s to ~7s, so it should to *something*. Please report back if/when you had time to try it out.

**Comment by 9999years** [comment]
@amesgen I rebased that branch on top of `fourmolu` and tried it out on our codebase and it took about 60 seconds to format the whole thing. (That's about as fast as it is passing `--no-cabal` and all the language extensions in manually.) So it looks your patch largely mitigates the regression we're seeing!

I'll note that still leaves the current ormolu _twice_ as slow as the old version, so it's not totally fixed, but this fix takes it from "untenable" to "workable" :)
