### ISSUE TITLE
Write with Unicode syntax when `UnicodeSyntax` is seen to be switched on?

### ISSUE THREAD

**Issue by kindaro** [tweag/ormolu#899]
I wanted to add an option to write Unicode syntax to `fourmolu` and [a maintainer there suggested][1] I check with the maintainers of `ormolu` if this can be merged here instead. So here I am. Would you merge that pull request?

[1]: https://github.com/fourmolu/fourmolu/pull/206#issuecomment-1160656273

**Comment by brandonchinn178** [comment]
Note: it wouldn't require an option if merged into Ormolu. It would be automatically applied, similar to how `ImportQualifiedPost` is [automatically handled](https://github.com/tweag/ormolu/blob/11cda4c653bc67a6ff579531a441410626ab3bbd/src/Ormolu/Printer/Meat/ImportExport.hs#L36)

**Comment by mrkkrp** [comment]
Seems to be not a very good idea if we keep in mind that the goal of a formatter is consistent appearance of the code. Some modules might end up using `UnicodeSyntax` and some not.

**Comment by brandonchinn178** [comment]
Couldnt you say the same thing about ImportQualifiedPost today? If someone turns it on for some modules and not others, it'll format qualified imports differently.

**Comment by mrkkrp** [comment]
I could, I wish that feature did not exist. Frankly, it doesn't solve any real practical issue and just complicates everything for a questionable cosmetic benefit.

I think the difference is that normalizing imports is a bit more troublesome (need to edit the AST), so a compromise was introduced there.
