### ISSUE TITLE
Ormolu incorrectly formats code with `-XOverloadedDot`

### ISSUE THREAD

**Issue by ocharles** [tweag/ormolu#900]
**Describe the bug**
Ormolu doesn't understand the significant of `OverloadedDot` and changes `foo.bar` into `foo . bar`, which changes the AST.

**To Reproduce**

Try and format

```haskell
{-# language OverloadedDot #-}

test = hello.world
```

**Expected behavior**
The semantics of `OverloadedDot` are respected, so `hello.world` remains unchanged.

**Environment**
 - OS name + version: NixOS 22.05
 - Version of the code: Formolu 0.7.0.1, but I imagine this is an Ormolu bug.

**Additional context**
No extra info.

**Comment by amesgen** [comment]
`OverloadedDot` is not a valid extension; Ormolu prints this exception:

```
  The GHC parser (in Haddock mode) failed:
  Unsupported extension: OverloadedDot
```

You probably mean `OverloadedRecordDot`, so the snippet 
```haskell
{-# language OverloadedRecordDot #-}

test = hello.world
```
is formatted to
```haskell
{-# LANGUAGE OverloadedRecordDot #-}

test = hello.world
```
as expected.

Does that resolve your question?

**Comment by ocharles** [comment]
Sorry, I meant `OverloadedRecordDot`. I must be on an old version... let me do a bit more testing. Thank for the polite fast response, and sorry I haven't really done enough diligence in reporting this!

**Comment by ocharles** [comment]
Ok, I found the problem - on our `master` branch we use `record-dot-preprocessor`, and I have a branch that ports all this to `OverloadedRecordDot`. I accidentally did this testing on `master` (and obviously Ormolu struggles because it has no idea that there's a preprocessor) - on the actual `OverloadedRecordDot` branch all is good. Thanks again for the prompt reply, and sorry for wasting your time!
