### ISSUE TITLE
GHC parser failure with nested block comment in haddock

### ISSUE THREAD

**Issue by brandonchinn178** [tweag/ormolu#904]
**Describe the bug**
When a pragma comment is in a haddock, GHC fails to parse.

**To Reproduce**
```hs
{-| {- bar -} -}
```

**Expected behavior**
Should pass.

**Environment**
 Tested this on ormolu-live.tweag.io

**Additional context**

**Comment by brandonchinn178** [comment]
Update: this parses:
```hs
{-| {\- bar -\} -}
```

**Comment by mrkkrp** [comment]
If the GHC parser fails on this, what can we do about it?

**Comment by brandonchinn178** [comment]
Moved to https://gitlab.haskell.org/ghc/ghc/-/issues/20336
