### ISSUE TITLE
Comment in empty export list moved out

### ISSUE THREAD

**Issue by brandonchinn178** [tweag/ormolu#906]
**Describe the bug**
```hs
module Foo
  ( {- comment -}
  )
where
```
gets reformatted to
```hs
module Foo
  (
  )
where

{- comment -}
```

Related: #901 

**To Reproduce**

**Expected behavior**
It should keep the comment in the export list

**Environment**
 - OS name + version: MacOS
 - Version of the code: HEAD

**Additional context**
This isn't an issue if there's anything in the export list, before or after the comment. So it's normally not an issue, since one usually exports at least one thing. But it's messing up my new library, which generates an export item at the spot specified by the comment. I currently workaround with a hack involving named sections, which is fine for my purposes, since haddocks aren't generated for tests:

https://github.com/brandonchinn178/tasty-autocollect/blob/f4890360a4870d2740e01d2c54f424b07c0ef88d/test/Test/Tasty/Ext/TodoTest.hs#L5

**Comment by brandonchinn178** [comment]
@amesgen hm this seems to break with block comments:
```hs
module Foo
  ( {- asdf -}
  )
where
```
Format without checking idempotence:
```hs
module Foo
{- asdf -}(
          )
where
```
Fixed point:
```hs
module Foo
{- asdf -} (
           )
where
```

**Comment by amesgen** [comment]
Thanks, that is unfortunate, I will have a look at this, especially as your PR #933 handles this properly. For some context from my POV:

 - The current comment layout logic has several very nice properties:
    - You basically don't have to think about comments while writing printing code; they are emitted automatically via `located`, which is very convenient and a significant reduction in cognitive load.
    - The comment printing logic is separated from printing the AST. 
    - It *generally* produces very good to decent output, and when it does not, it is usually easy to put the comment in a slightly different place for it to work.
 - OTOH, almost all currently open bugs are related to comments (in particular idempotence), and many style requests are also related to comments (one of the most prominent ones: #469).
 - It is probably possible to fix most of these issues by adding lots of special cases, and also starting to interleave comment and AST printing. Any individual such fix is probably not a big deal, but together, they could introduce significant complexity, in particular to the comparatively low severity of the issues they are resolving.
 - "Proper" solutions could include:
    - Fix these problems by identifying a self-contained change the existing comment printing logic.
    - Switch to a completely different way of printing comments, e.g. using the comment-to-AST association present in the GHC AST via TTG/EPA (trees-that-grow/exact-print-annotations); also see #324 for some considerations.
