### ISSUE TITLE
Parse error on input `where'

### ISSUE THREAD

**Issue by andys8** [tweag/ormolu#921]
**Describe the bug**

Trying to format a compiling file resulted in a parse error.

**To Reproduce**

https://github.com/haskell/haskell-language-server/blob/5d35a740b2fd70b225aaa94541ff22c3ed3e060a/plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs#L611

* `git clone haskell/haskell-language-server`
* Checkout `5d35a740b2fd70b225aaa94541ff22c3ed3e060a` (in case of changes)
* `ormolu plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs`

```shell
ormolu plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs
plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs:611:5-9
  The GHC parser (in Haddock mode) failed:
  parse error on input `where'
```

**Expected behavior**

Formats without issue

**Environment**
 - OS name + version: Manjaro 22.0.0
 - Version of the code: ormolu 0.5.0.1 HEAD f80f4ec20d6758531914497fefc03d30c55b48d0 using ghc-lib-parser 9.2.1.20220109

**Comment by amesgen** [comment]
The file you linked uses CPP, which Ormolu does not/can not fully support, see https://github.com/tweag/ormolu#limitations

In such situations, using Ormolu's [magic comments](https://github.com/tweag/ormolu#magic-comments) in appropriate places usually the best path forward.
