### ISSUE TITLE
Cut a release for GHC 9.4

### ISSUE THREAD

**Issue by 9999years** [tweag/ormolu#937]
With #885 merged, Ormolu is now ready for GHC 9.4! However, a new release hasn't been uploaded to Hackage, so it's not yet usable by the wider community. Let's cut a release for GHC 9.4!

**Comment by mrkkrp** [comment]
Yes, we know. It is not cut because we might want to include more changes such as #933.

**Comment by 9999years** [comment]
Glad to hear it's coming soon! Can we leave this open until it's done, though?
