### ISSUE TITLE
Improve handling of newline before functions bodies

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#94]
Currently we use a "normal" `breakpoint` between equal sign `=` of function definitions and body functions. This means that there will be a space if the body is a one-liner and a newline otherwise. This leads to this sort of transformation:

```haskell
-- input:
instance Stream BL.ByteString where
  reachOffset o pst =
    reachOffset' splitAtBL BL.foldl' BL8.unpack (chr . fromIntegral) (10, 9) o pst

-- output:
instance Stream BL.ByteString where
  reachOffset o pst = reachOffset' splitAtBL BL.foldl' BL8.unpack (chr . fromIntegral) (10, 9) o pst
```

Which is obviously wrong because now the line is too long. We should start respecting those newlines.

N.B. I guess this is applicable to any match groups, not only function definitions.

**Comment by ruhatch** [comment]
This does indeed apply to `case` statements as well

**Comment by ruhatch** [comment]
So I've been working through this and it seems the best way to handle this is to extend the `SrcSpan` from the body to include the *last line* of the name/pattern part of the match group. This allows us to have multiline patterns, while preserving single line bodies. I will try to get a PR for this in soon.

**Comment by mrkkrp** [comment]
Re-opened. The PR #116 solves the problem only partially. For example if I have this in a where clause:

```
   where
-    queryLocated (L mspn _) =
-      case cast mspn :: Maybe SrcSpan of
-        Nothing -> mempty
-        Just (UnhelpfulSpan _) -> mempty
-        Just (RealSrcSpan spn) -> D.singleton spn
+    queryLocated (L mspn _) = case cast mspn :: Maybe SrcSpan of
+      Nothing -> mempty
+      Just (UnhelpfulSpan _) -> mempty
```

**Comment by mrkkrp** [comment]
@ruhatch Do you want to make another attempt on this? I think it has relatively high priority right now. If you can't I could pick it up when I have time.

**Comment by mrkkrp** [comment]
It appears that with the present code it is quite difficult to do the change. We need to re-think the `Value` module and find a way to make it manageable and easier to understand.
