### ISSUE TITLE
Accept (also) command line options from an environment variable

### ISSUE THREAD

**Issue by maridonkers** [tweag/ormolu#942]
**The problem**
For a Haskell cabal project ormolu requires the `--stdin-input-file  pathtocabalfile` option, which is fine. But when ormolu is used from within Emacs via e.g. `format-all` then this command line option cannot be easily supplied.

**Suggested solution**
Have ormolu accept an environment variable that can contain command line options (in addition to those specified on the command line). Then e.g. Emacs can be started from a cabal project directory as follows:

```sh
ORMOLU_OPTIONS="--stdin-input-file `pwd`" emacs src/Main.hs
```

**Alternative (workaround)**
 Currently I use a workaround where a manual change to the `format-all.el` Emacs package's source code and byte-compile'ing it makes it call `ormolu.sh` instead of ormulu and the in-between shell file supplies the option, as follows:

ormolu.sh:
```sh
#!/bin/sh

ormolu --stdin-input-file ${CABAL_PROJECT} $*
```
The `CABAL_PROJECT` variable is set prior to calling Emacs (from a Makefile), as follows:

```makefile
edit:
        CABAL_PROJECT=`pwd` emacs &
```

(This works but at every update of the `format-all` Emacs package the change to the source code gets overwritten.)

**Additional context**
The error that is reported by ormolu is as follows:

```
The --stdin-input-file option is necessary when using input from stdin and accounting for .cabal files
```

**Comment by ocharles** [comment]
If this is the right `format-all.el`, it looks like you can just add your own formatter: https://github.com/lassik/emacs-format-all-the-code/blob/master/format-all.el#L1035. You could have a `custom-ormolu` formatter that calls your `ormolu.sh`.

**Comment by amesgen** [comment]
In addition to what @ocharles already said, you can see how we set `--stdin-input-file` in `ormolu.el`: https://github.com/vyorkin/ormolu.el/blob/a6b1d3f8838d067ac5352fb0673c3c3dae7abd73/ormolu.el#L65-L67

If you find a solution, we could mention it in the [list of editor integrations](https://github.com/tweag/ormolu#editor-integration).

---

Just to clear up a possible confusion of how `--stdin-input-file` works:

> For a Haskell cabal project ormolu requires the `--stdin-input-file pathtocabalfile` option

 - You don't have to provide this option if you set `--no-cabal` (but then e.g. `default-extensions` are ofc. not respected).
 - The path argument (which you named `pathtocabalfile`) should **not** be the path to your `.cabal` file or your project directory:
   
   > When input comes from stdin, one can pass `--stdin-input-file` which will give Ormolu the location of the Haskell source file that should be used as the starting point for searching for a suitable Cabal file.

   https://github.com/tweag/ormolu#language-extensions-dependencies-and-fixities

   If you run Ormolu with the respective flags in your terminal, you will see a warning when no `.cabal` file could be located of if the located `.cabal` file does not contain a module corresponding to the `--stdin-input-file`, which should always be the case when you pass in your project directory via `--stdin-input-file`.

**Comment by maridonkers** [comment]
> If this is the right `format-all.el`, it looks like you can just add your own formatter: https://github.com/lassik/emacs-format-all-the-code/blob/master/format-all.el#L1035. You could have a `custom-ormolu` formatter that calls your `ormolu.sh`.

Thanks, I wasn't aware of custom formatter functionality in `format-all`; looks like a nice solution, will investigate.

**Comment by maridonkers** [comment]
> 
> Just to clear up a possible confusion of how `--stdin-input-file` works:
> 
> > For a Haskell cabal project ormolu requires the `--stdin-input-file pathtocabalfile` option
> 
> * You don't have to provide this option if you set `--no-cabal` (but then e.g. `default-extensions` are ofc. not respected).
> * The path argument (which you named `pathtocabalfile`) should **not** be the path to your `.cabal` file or your project directory:
>   > When input comes from stdin, one can pass `--stdin-input-file` which will give Ormolu the location of the Haskell source file that should be used as the starting point for searching for a suitable Cabal file.

Aha, now I understand the name  `--stdin-input-file` which supplies a filename when none is knwon because of stdin.
   
>   https://github.com/tweag/ormolu#language-extensions-dependencies-and-fixities
>   If you run Ormolu with the respective flags in your terminal, you will see a warning when no `.cabal` file could be located of if the located `.cabal` file does not contain a module corresponding to the `--stdin-input-file`, which should always be the case when you pass in your project directory via `--stdin-input-file`.

I understand but passing in my project directory does work (ormolu formats my Emacs buffer, without the error `--stdin-input-file` message. I'll check if the custom formatter suggested by Ollie Charles — which works BTW — can take a `--stdin-input-file filenameforbuffer`.

**Comment by amesgen** [comment]
> Aha, now I understand the name --stdin-input-file which supplies a filename when none is knwon because of stdin.

Exactly :+1:

> I understand but passing in my project directory does work (ormolu formats my Emacs buffer, without the error `--stdin-input-file` message. 

Yes, but it is not actually picking up anything from your `.cabal` file, which might not be a problem if your file does not need any extensions that are not enabled by default. When you run the command in your terminal, you will see a warning on stderr, quoting from my message above:

> * If you run Ormolu with the respective flags in your terminal, you will see a warning when no `.cabal` file could be located of if the located `.cabal` file does not contain a module corresponding to the `--stdin-input-file`, which should always be the case when you pass in your project directory via `--stdin-input-file`.

The point of the `.cabal` file reading feature is that there might be e.g. extensions in your `.cabal` file that are necessary to correctly parse and format your source file. Ormolu has most of them enabled by default (i.e. purely "additive" features that don't change existing code), but not all extensions are of this kind, see `ormolu --manual-exts`.

As an example, consider the snippet
```haskell
foo = record.bar
```
which will be parsed differently with or without `OverloadedRecordDot` (accessing a record field vs function composition). Hence, if you have `OverloadedRecordDot` in your `.cabal` file via `default-extensions`, Ormolu will still format it even if you pass it an incorrect argument via `--stdin-input-file`, but the result will be a function composition, namely
```haskell
foo = record . bar
```
which is not what you want.

**Comment by maridonkers** [comment]
The custom formatter suggestion by Ollie Charles also allows for a parameter to be passed; I've listed the source code section of my emacs config in the [comment above](https://github.com/tweag/ormolu/issues/942#issuecomment-1328101105). Which BTW is already used for `fourmolu` in `format-all`'s source code. Thanks for all the feedback; shall I close this issue?

**Comment by amesgen** [comment]
If there is no outstanding unclarity/question, then go ahead, but feel free to comment here again of course :smile:

**Comment by maridonkers** [comment]
> If there is no outstanding unclarity/question, then go ahead, but feel free to comment here again of course smile

Will do :-) Also I'll ask at [lassik/emacs-format-all-the-code](https://github.com/lassik/emacs-format-all-the-code) why the default config for `fourmolu` has the `--stdin-input-file` parameter but the default config for `ormolu` hasn't.
