### ISSUE TITLE
Improve the way operators are chained

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#95]
There are few issues with current formatting of chains of operators. First of all, I think we should revert to this style with operator on the second line before the second argument:

```haskell
foo
  + bar
```

and in a sequence it should be:

```haskell
foo
  + bar
  + baz
```

This will allow us to have reasonable rendering of e.g. applicative notation.

`do`-notation should be treated specially:

```haskell
foo
  + bar
  + baz $ do
```

Also, things applied before `do` with `($)` should still make the whole construction hanging:

```haskell
foo = foo $ do
  ...
````

vs current:

```haskell
foo =
  foo $ do
    ...
```

The change described in #94 should then still allow users to have a newline before such constructions involving `do`.

**Comment by facundominguez** [comment]
```
bar =
  foo $ do
    ...
```
I find this more readable than
```
bar = foo $ do
    ...
```

When the do block is large I have failed to notice the `foo` application to the block more than once, but YMMV.

**Comment by neongreen** [comment]
This also affect a common lens idiom. Before:

```haskell
foo = bar
  & a .~ b
  & c .~ d
  & e .~ f
```

After:

```haskell
foo =
  bar &
    a .~
    b &
    c .~
    d &
    e .~
    f
```
