### ISSUE TITLE
Online formatter should allow copying parts of the output

### ISSUE THREAD

**Issue by asarkar** [tweag/ormolu#951]
Why prevent copying from the output pane? Often times I don't want to copy everything, just a portion of it, and execute that part of the code.

**Is your feature request related to a problem? Please describe.**
The online formatter doesn't allow copying portions of the code.

**Describe the solution you'd like**
It should be possible to select and copy portions of output, although editing shouldn't be allowed.

**Describe alternatives you've considered**
Copy-pasting into a text editor.

**Additional context**
N/A

**Comment by amesgen** [comment]
I guess this can be closed once #964 is merged as selecting text in the output does work there?

**Comment by asarkar** [comment]
If you link this issue with the commit, it'll get closed automatically when the commit is merged.
