### ISSUE TITLE
Replace SYB by Uniplate

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#96]
It appears that Uniplate is a more modern, better maintained library compared to SYB. Let’s try to switch to Uniplate.

**Comment by mboes** [comment]
I mean, Uniplate is great. And might have been a better starting choice. But is there a particular impetus that would justify the switching cost? What is SYB used for currently?

**Comment by mrkkrp** [comment]
Now that I know more about Uniplate, I’m not sure that we need to do the switch. Let’s close this one for now.

**Comment by neongreen** [comment]
I'm curious what did you learn about Uniplate that made you decide against the switch.

**Comment by mrkkrp** [comment]
The main point of `uniplate` is that it's faster.

* `syb` transformations are not the bottleneck our us.
* It is necessary either manually define some typeclasses such as `Biplate` to make `uniplate` work, or to use some code-generation things (not even TH). Both of which seem unhandy with GHC AST. If we do not define those type classes we can still do it via `Data` but it's the same technique we already use with `syb`.
