### ISSUE TITLE
Unindent list comprehension

### ISSUE THREAD

**Issue by brandonchinn178** [tweag/ormolu#966]
**Describe the bug**

Personally, I find that reformatting this:
```hs
x =
  [ i + 1
  | i <- [0 .. 5]
  ]
```
to:
```hs
x =
  [ i + 1
    | i <- [0 .. 5]
  ]
```
to be very surprising. I understand this for things like parallel list comprehension or in a do-block, but IMO a simple list comprehension should not indent like this

**Comment by mrkkrp** [comment]
Resolved in #1119.
