### ISSUE TITLE
Is String type considered legacy?

### ISSUE THREAD

**Issue by yaitskov** [tweag/ormolu#972]
I have a look into Ormolu code base. 
It is using `String` type everywhere. Is there expectations that switching to `Data.Text` would provide performance gain? 

Recently, on Haskell Weekly I saw an article about xhtml library refactoring shifting towards Text.

**Comment by yaitskov** [comment]
https://www.parsonsmatt.org/2022/12/21/haddock_performance.html

**Comment by amesgen** [comment]
That is a funny coincidence, see #963 :smile:

See the benchmarks there for how much of a speedup that yields, but be aware that this is not necessarily a representative example of the expected speedup across all workloads; Ormolu does already use `Text` and other appropriate data structures in most places that matter.
