### ISSUE TITLE
cabal inside nix-shell is not working

### ISSUE THREAD

**Issue by yaitskov** [tweag/ormolu#973]
nix-shell starts shell but cabal is not working.

```
[nix-shell:~/pro/ormolu]$ type haskell-language-server
haskell-language-server is /nix/store/cm22flslgspfffa0zwasgzdj8mlfmvmn-haskell-language-server-exe-haskell-language-server-1.8.0.0/bin/haskell-language-server

[nix-shell:~/pro/ormolu]$ type ghc
ghc is /nix/store/9wdivs4vd0gii68d74rw3l6a6dl0c1ap-ghc-shell-for-ormolu-ghc-9.2.4-env/bin/ghc

[nix-shell:~/pro/ormolu]$ type cabal
cabal is hashed (/nix/store/x2ribvhlx8vs7sdg4x993x05xjr86d3b-cabal-install-exe-cabal-3.8.1.0/bin/cabal)

[nix-shell:~/pro/ormolu]$ git log -1
commit 708de707ad44172d9a6019e6f09b48ddc3782170 (HEAD -> master, origin/master, origin/HEAD)
Author: Alexander Esgen <alexander.esgen@tweag.io>
Date:   Fri Jan 6 14:40:38 2023 +0100

    Stop making empty `let`s move comments
```

```

[nix-shell:~/pro/ormolu]$ cabal build
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: extract-hackage-info-0.0.0.0 (user goal)
[__1] unknown package: tagsoup (dependency of extract-hackage-info)
[__1] fail (backjumping, conflict set: extract-hackage-info, tagsoup)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: extract-hackage-info, tagsoup


[nix-shell:~/pro/ormolu]$ cabal exec -v0 -- ghc --print-libdir
Error: cabal: Could not resolve dependencies:
[__0] trying: extract-hackage-info-0.0.0.0 (user goal)
[__1] unknown package: tagsoup (dependency of extract-hackage-info)
[__1] fail (backjumping, conflict set: extract-hackage-info, tagsoup)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: extract-hackage-info, tagsoup

```

deleting ~/.cabal doesn't help.

**Comment by amesgen** [comment]
I think this should be fixed if you run
```console
cabal update
```
before trying to build. The reason is a not immediately obvious Cabal behavior: Even when you build just a single module of a multi-package project (like Ormolu), Cabal wants to find a build plan encompassing *all* components even though it won't build anything for those. That means that you have to have a (somewhat recent) Hackage index available, which you can get via `cabal update`.

**Comment by mrkkrp** [comment]
@amesgen Do you know how does it interact with `nix-shell`? When I build inside `nix-shell` it certainly uses a different set of packages (those provided by Nix, presumably) compared to invoking `cabal` outside of `nix-shell`. If this is true, then inside `nix-shell` `cabal` should work regardless of the state of the "outside" world.

**Comment by amesgen** [comment]
> When I build inside `nix-shell` it certainly uses a different set of packages (those provided by Nix, presumably) compared to invoking `cabal` outside of `nix-shell`.

Yes, it will only use haskell.nix-provided dependencies; but in the main shell, we only provide those for the `ormolu` package (library, executable and test suite), as you can see here:

https://github.com/tweag/ormolu/blob/9e4f22e14c2213981e8437d13e9d7000218bffb1/default.nix#L102-L104

This was motivated by the fact that `ormolu-live` and `extract-hackage-info` had/have additional dependencies compared to just `ormolu`, and it would be annoying to have to build them if you are not interested in working with them ATM. But this is exactly what triggers the behavior above (Cabal wanting to find a build plan for all packages in a project even if it is only building a single package). If we would use one shell for all packages, `cabal update` should not be necessary.

In general, I don't think that requiring that someone ran `cabal update` some time ago is too bad, as it is e.g. already required for useful commands like `cabal outdated` to work.

In any case, I actually already changed this in #940, as `ormolu` already implies almost all dependencies of `extract-hackage-info`:

https://github.com/tweag/ormolu/blob/119dcc60c277af8cc84cd20d2cbbd79ee7c2d616/flake.nix#L129

**Comment by yaitskov** [comment]
Thanks, `cabal update` helps. 

Why not to append `cabal update` to shell hook then?

**Comment by yaitskov** [comment]
https://github.com/tweag/ormolu/pull/974
