### ISSUE TITLE
Howto activate OverloadedRecordDot extension

### ISSUE THREAD

**Issue by agreif** [tweag/ormolu#977]
Hi,
where and how can I activate the OverloadedRecordDot extension?
I already added it to my Cabal File but that has no effect.
Does it go into a .ormolu file? If yes, what is the syntax?

Thanks,
Alex.

**Comment by amesgen** [comment]
Ormolu will be aware of the `OverloadedRecordDot` extension when you add it as a pragma to the top of your file
```haskell
{-# LANGUAGE OverloadedRecordDot #-}
```
or in your `.cabal` file via `default-extensions`
```cabal
default-extensions: OverloadedRecordDot
```
or when you invoke the `ormolu` binary with `-o -XOverloadedRecordDot`.

Can you maybe post a minimal example of your setup? Otherwise, it is a bit difficult to diagnose what is going on.

**Comment by agreif** [comment]
Thanks,
I was missing the `-X` in `-o -XOverloadedRecordDot` ... now it works.

The language pragma in the `.hs` file also works.

`default-extensions:` in my `.cabal` does not work ... I get this this output:
```
$ ormolu -m inplace Web/Controller/Login.hs
Found .cabal file App.cabal, but it did not mention Web/Controller/Login.hs
```
Does the file has to be explicitly given in the cabal file?
My `.cabal` file looks like:
```
name:                App             
version:             0.1.0.0         
-- synopsis:                         
-- description:                      
license:             AllRightsReserved                                     
license-file:        LICENSE         
author:              Developers      
maintainer:          developers@example.com                                
-- copyright:                        
-- category:                         
build-type:          Simple          
cabal-version:       >=1.10                                                

executable App                       
  main-is:             Main.hs       
  -- other-modules:                  
  -- other-extensions:               
  build-depends:                     
        ihp,                         
        base,                        
        wai,                         
    text                             
  hs-source-dirs:      .             
  default-language:    Haskell2010                                         
  extensions:                        
    OverloadedStrings                
    , NoImplicitPrelude              
    , ImplicitParams                 
    , Rank2Types                     
    ...
  default-extensions: OverloadedRecordDot
```

**Comment by amesgen** [comment]
> Does the file has to be explicitly given in the cabal file?

Exactly, as you might have different extensions enabled in different components (e.g. executable vs library). That is what the message
```
Found .cabal file App.cabal, but it did not mention Web/Controller/Login.hs
```
is about.

**Comment by agreif** [comment]
ok, thanks. I close this issue
