### ISSUE TITLE
Poly-kinded datatypes cause Ormolu parse errors, given a newline between forall and kind

### ISSUE THREAD

**Issue by zlindenbaum** [tweag/ormolu#979]
**Describe the bug**
Ormolu throws a parse error when, in a poly-kinded datatype declaration, the kind's forall statement and the kind signature are separated by a newline. This is especially noticeable, because it's the format to which a template-haskell poly-kinded datatype generator de-splices.

**To Reproduce**
```
data PolyKindedType :: forall a.
                       a -> Type
 where
  PolyKindedType :: PolyKindedType Integer
```

**Expected behavior**
Ormolu should format the above as
```
data PolyKindedType :: forall a. a -> Type where
  PolyKindedType :: PolyKindedType Integer
```
Indeed, it does so when forall and kind are not whitespace separated, as in the below
```
data PolyKindedType :: forall a. a -> Type
 where
  PolyKindedType :: PolyKindedType Integer
```

**Environment**
 - OS name + version: NixOS 22.11.1574.6a3f9996408 (Raccoon)
 - Version of the code: Ormolu 0.3.1.0

**Comment by amesgen** [comment]
I can't reproduce this on Ormolu 0.5.2.0 (latest release) or on [Ormolu Live](https://ormolu-live.tweag.io/) (points to latest commit on `master`).

Can you confirm that upgrading Ormolu fixes the issue?

**Comment by amesgen** [comment]
Hmm, Ormolu [0.3.1.0](https://github.com/tweag/ormolu/releases/tag/0.3.1.0) actually also works fine for me (with the same output), can you post the parse error message you are seeing?

**Comment by zlindenbaum** [comment]
Apologies - some nix-shells through me for a loop. It threw a parse error on version 0.1.4.1; 0.3.1.0 parses it just fine.
