### ISSUE TITLE
Combining where and do will fail

### ISSUE THREAD

**Issue by waddlaw** [tweag/ormolu#98]
Input:

```haskell
f :: Maybe Int
f = do
  return c
  where
    c = 0
```

```
λ ormolu A.hs
Parsing of formatted code failed:
<rendered>:3:1-5
parse error on input ‘where’
Please, consider reporting the bug.
```

**Comment by ruhatch** [comment]
I think there's quite a strong argument here for having `where` clauses use 1 space in this case. The reason is to reduce diffs, so if we go from:
```
f :: Maybe Int
f = do
  return 0
```
to
```
f :: Maybe Int
f = do
  return c
 where
  c = 0
```
then we don't have to indent the body of the `do` any further. This keeps diffs small and preserves parsablility.
