### ISSUE TITLE
ormolu does not handle Unicode correctly

### ISSUE THREAD

**Issue by Ptival** [tweag/ormolu#995]
**Describe the bug**
When ormolu rewrites lines that contain Unicode, it frequently leaves extra characters in the output.

**To Reproduce**
Format the following file
```haskell
module Unicode where
testing 𝓋 τ =
  let c ↦ d = id
  in (𝓋 ↦ τ) False
```

**Expected behavior**
Code formatted properly. Instead we get:
```haskell
module Unicode where
testing 𝓋 τ =
  let c ↦ d = id
   in (𝓋 ↦ τ) Falsee -- Note the extra 'e'
```

**Comment by mrkkrp** [comment]
What version of Ormolu are you using? Can you reproduce it on https://ormolu-live.tweag.io/ ? (I could not.)
